### ISSUE TITLE
Connect Realms support

### ISSUE THREAD

**Issue by Deavan** [Xruptor/BagSync#10]
It would be good to be able to see what you have on all realms that are part of a connected realm instead of just the realm you are currently on.

When updating BagSync to add Connected Realm support remember that someone may have characters on more than one set of connected realms.

**Comment by Xruptor** [comment]
After thinking about this, I've come to the conclusion that this will be quite a pain to keep track of.  I would have to have an updated list of all connected realms and make sure it's always updated.  This list would be broken into blocks where each block contains the list of realms that are connected to each other.  Unless there is an API that blizzard provides that returns if a realm is connected or not, I don't see this as being something easily implemented.  I just don't have enough time anymore to make this a reality.  If someone else wants to tackle it then that's great and I'll be more then glad to merge the changes.  Otherwise, I don't see this being implemented anytime soon.  I apologize.
