### ISSUE TITLE
Messes up the Auction House

### ISSUE THREAD

**Issue by akis-t** [Xruptor/BagSync#101]
When it is installed and active opening the AH takes a long tiem to bring in the favorites, posting items does not "catch" and you need to do it repeatedly, all those problems go away once deactivated.

**Comment by Xruptor** [comment]
> When it is installed and active opening the AH takes a long tiem to bring in the favorites, posting items does not "catch" and you need to do it repeatedly, all those problems go away once deactivated.

The posting items doesn't catch all the time because the new Blizzard Auction House is currently broken.  They need to fix it to allow developers to grab items properly.  Right now I have to use a repeating timer to constantly look over the items to see if anything has been posted.  But this can get interrupted by things like navigating around the auction house, reviewing other items, doing a search, etc.. etc..  Each time the timer resets.  It also terminates when you close the auction house.

There is currently no way around this sorry.  The only solution I can offer is to turn off the Auction House stuff for right now in the options panel.

In terms of the favorites?  That is something I haven't taken a look at it and it may be currently bugged in the BagSync code.  I didn't really look too much into the favorites.  I'll take a look at asee if it's something I can patch up.

**Comment by akis-t** [comment]
Click on the AH, with the addon disabled you get your list of favourites within ms, with the addon active it may take many seconds until the favourites appear.

**Comment by Xruptor** [comment]
> Click on the AH, with the addon disabled you get your list of favourites within ms, with the addon active it may take many seconds until the favourites appear.

I'll take a look at the favorites.  It could be just a display issue.

But like I said in terms of the posting of items that is beyond my control.  I was contacted and they are aware of the issue but haven't patched it.
[https://us.forums.blizzard.com/en/wow/t/getnumownedauctions-and-getownedauctioninfo-not-properly-updating/424237](url)

**Comment by akis-t** [comment]
Yes I can confirm disabling the "Display AH items" fixes it.

**Comment by Xruptor** [comment]
[BagSync-Test.zip](https://github.com/Xruptor/BagSync/files/4439284/BagSync-Test.zip)

Please try the above version.  Make sure to turn Auctions back on.
Let me know if you still get the lag and or long spinning times for things like your favorites.

**Comment by akis-t** [comment]
It worked on first opening of the AH, from there on it cashed the AH and
kept crashing it.

**Comment by akis-t** [comment]
It worked first time I opened the AH, but did not work subsequently, it crashed the AH instead.

**Comment by Xruptor** [comment]
> It worked first time I opened the AH, but did not work subsequently, it crashed the AH instead.

That is so completely odd.  Lets try a few things.

1) Do you have any other addon that interacts with the Auction House?

2) Try disabling ALL addons, **except BagSync**.  Use the Auction House and see if you still get the same problem.

3) How many items do you have as favorites?  Do you have lots of items up for sale?

4) Please provide me a screenshot of your UI while using the Auction House.  Gives me a better idea of what's going on.

**Comment by Xruptor** [comment]
It's been a bit.  Haven't heard back from you?  Not sure if the bug was fixed or there was another addon conflicting.  If possible please answer the questions above.

**Comment by Xruptor** [comment]
Um okay?  Still haven't heard back from you.  If I don't hear back soon I'm just going to close this ticket.

**Comment by akis-t** [comment]
Hi, sorry, yes the zip file you sent to me still messes up my AH, this time the AH locked completely. I have about 65 items in my favourites. I have uninstalled this addon for the time being. Actually my use case is simply the inventory across my alts, I do not want or need anything heavier at the moment. Maybe you can try testing with someone that makes more use of the AH ? As a wild guess / hint, there are times where the AH does not send you full information, yet, the Blizzard AH UI, still displays all the items and you would not know some information was missing (item info I think), but maybe your addon waits for everything to come through and "locks" the default AH UI during this time?

**Comment by Xruptor** [comment]
> Hi, sorry, yes the zip file you sent to me still messes up my AH, this time the AH locked completely. I have about 65 items in my favourites. I have uninstalled this addon for the time being. Actually my use case is simply the inventory across my alts, I do not want or need anything heavier at the moment. Maybe you can try testing with someone that makes more use of the AH ? As a wild guess / hint, there are times where the AH does not send you full information, yet, the Blizzard AH UI, still displays all the items and you would not know some information was missing (item info I think), but maybe your addon waits for everything to come through and "locks" the default AH UI during this time?

The issue with the Queries is not that BagSync is forcing it, it's that the new AH has a throttle system and does not allow queries to be sent during a throttle process.  It causes complications and infinite loop scenarios on the AH.  It's by design a very poor design and many developers are a bit angry at the new AH changes.  It causes more headaches than anything else.

I added a delay in to the BagSync scan that waits for the server response. I've been testing it and it seems to work.  It now waits for several things before it tries to parse the AH.  Try giving this updated version a go.

[BagSync-Test.zip](https://github.com/Xruptor/BagSync/files/4466565/BagSync-Test.zip)
