### ISSUE TITLE
error

### ISSUE THREAD

**Issue by realrobd** [Xruptor/BagSync#103]
1x [ADDON_ACTION_BLOCKED] AddOn 'BagSync' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\SecureStateDriver.lua"]:10: in function <FrameXML\SecureStateDriver.lua:8>
[string "=(tail call)"]: ?
[string "@ElvUI\Modules\UnitFrames\UnitFrames.lua"]:1003: in function `CreateAndUpdateHeaderGroup'
[string "@ElvUI\Modules\UnitFrames\UnitFrames.lua"]:1092: in function `UpdateAllHeaders'
[string "@ElvUI\Modules\UnitFrames\UnitFrames.lua"]:879: in function `HandleSmartVisibility'
[string "@ElvUI\Modules\UnitFrames\UnitFrames.lua"]:884: in function `?'
[string "@BagSync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BagSync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ync\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@BagSync\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@BagSync\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...ceBagSync\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Xruptor** [comment]
This is a taint issue associated with any addon you may have installed.

Taint issues or protected functions can be blamed on an addon even if the addon didn't trigger it (meaning another addon caused it). It's a known issue with how Blizzard handles taints. The way it happens is when an taint or protected function error is triggered at that precise moment, whatever addon is currently running will get blamed.  Yes, even if it's not that addon that caused the issue in the first place. Since there is no real way to determine which addon caused the taint issue, it's very difficult to fix.  You can view the taint log that blizzard provides but it's a huge mess. All it does it tell you a trail of various addons that may have caused the issue.  But it doesn't tell you what addon, where in the code it occurred, or what triggered it.

For more information how terrible the Blizzard taint and protected system is, please visit this site 😄
https://defectivetanking.wordpress.com/2014/01/18/wows-taint-system-addons-and-why-classic-was-so-much-easier/

Sadly Blizzard's taint system is completely broken and it blames all sorts of addons indirectly even if they didn't trigger it. It's been an issue with addons for ages now for as long as I can remember. Most people nowadays just disable taint log and disable taint stuff in their bug swatter addons.

Even ElvUI and TukUI suffer from this problem.
https://www.tukui.org/forum/viewtopic.php?t=9344
