### ISSUE TITLE
Tooltip extra space on pet battles! can provide screenshot.

### ISSUE THREAD

**Issue by strickland** [Xruptor/BagSync#104]
I'm a pet battler, I use some other addons such as pettracker, auctionator, rematch etc.

I also use Bagsync and adibags for my bags, tooltip look great except for battle pets.

Here's battle pet tooltip without bagsync SS.
https://imgur.com/a/HnMVDLW
https://imgur.com/a/YxnQjGW

Here's battle pet tooltip WITH bagsync SS. (Note the extra spaces)
https://imgur.com/a/OU3qBvq
https://imgur.com/a/YdoOuj2

**Comment by Xruptor** [comment]
That is totally weird.  Can you give me a list of the addons you do have installed?  It looks like it's reading the lines an adding a space after every line.

**Comment by strickland** [comment]
Sure, list of addons.

https://imgur.com/a/sTQtCvf
https://imgur.com/a/GzVcjrA

page 1 and page2.

**Comment by Xruptor** [comment]
> Sure, list of addons.
> 
> https://imgur.com/a/sTQtCvf
> https://imgur.com/a/GzVcjrA
> 
> page 1 and page2.

Thanks I'm going to take a look at this. I'm not entirely sure why empty lines are being added. Since it should be just parsing the text and only apply data after a pet has been found. While I try to debug this.  Please do me a favor and enable the Enhanced Tooltips feature of BagSync and tell me what that does. You may have overlapping tooltips but I'm not sure.  In the meantime I'll see if I can reproduce this issue.

**Comment by strickland** [comment]
Thank you.

**Comment by Xruptor** [comment]
Hey I'm still trying to replicate this issue on my spare time. As of yet I cannot seem to pinpoint the problem. I've tried several workarounds but I think something else is tampering with the BagSync tooltip display.  I'll keep you posted.

**Comment by strickland** [comment]
no worries, thank you very much! I can live with it btw, I'm just notifying you that it happens, do whatever you want.
