### ISSUE TITLE
add new feature for gold tooltip 

### ISSUE THREAD

**Issue by createaaccountishard** [Xruptor/BagSync#105]
hello. i using the bagsync in wow classic v13.6.
when i open the package and move mouse to zhe gold , there is no tooltip to show gold total.
and when i set the keyshort "/" to gold tooltip,  it only show  but not dimiss.  it is not a goog feel that i click double .
and it will go to the center in screen ,throuth i move it to anther aree.

coulde you update the version ? i hope :
1 when i click double times ,the windonws could dimiss
2 when i move the gold tooltip ,it will show in the next show.
3 the gold tooltip could show in the bag gold area when the mouse on it

**Comment by createaaccountishard** [comment]
![avatar](/C:\Users\Emiya\Desktop\1.png)

**Comment by Xruptor** [comment]
I'll look into the tooltip issues. As for displaying the gold in the bag gold tooltip, the reason I haven't done this is because every cuistom UI and custom bag addon handles gold display differently. In order for me to do what you would like, I would have to add support for all these different UI's and custom bag addons.  Even if I did a catch-all, it wouldn't possibly be compatible with every UI.  I may put an experiemental checkbox for such a feature.  I'll look into it.

**Comment by Xruptor** [comment]
After looking into this there are just way too many graphical mods for the bags that would cause complications.  I would have to create custom hooks for all of them and I really don't want to do that.
