### ISSUE TITLE
Make profession and currency storage locale-independent.

### ISSUE THREAD

**Issue by LudiusMaximus** [Xruptor/BagSync#106]
When I change the language of my client and log in, I get duplicates of the professions and currencies in the other language.

**Comment by Xruptor** [comment]
That's a very interesting bug.  I made the profession and currency token use the currencyID for each token.  It's a unique number associated with each currency.  The fact that it's repeated for each localization language is interesting.  It shouldn't be doing that.  I'll have to take a look.

**Comment by LudiusMaximus** [comment]
To be honest, I noticed this with the version I forked one year ago. If you implemented the usage of currencyID within the last year, it might already be fixed. Sorry for not checking more thoroughly.

**Comment by Xruptor** [comment]
I made significant changes to the code over the course of the year.  A lot of it was impact performance and streamlining the code.  One of those changes was using CurrencyID instead of the Currency name.  If you forked it over a year ago you may want to do a code difference check using WinDiff or whatever other application to see the changes.

**Comment by Xruptor** [comment]
Just let me know if everything checks out.  That way I can close this ticket.

**Comment by LudiusMaximus** [comment]
In this case, don't worry. If there was in fact a change from using CurrencyID instead of name, then it's most likely fixed. Sorry for the fuss.
