### ISSUE TITLE
Error when opening profession window

### ISSUE THREAD

**Issue by wheatbread** [Xruptor/BagSync#114]
v14.1

I'm getting the following error when opening the profession window (tested on Inscription, Engineering, Alchemy, Enchanting):

`4x bad argument #2 to '?' (outside of expected range 0 to 4294967295 - Usage: local recipeInfo = C_TradeSkillUI.GetRecipeInfo(recipeSpellID [, recipeLevel]))
[string "=[C]"]: in function `GetRecipeInfo'
[string "@BagSync\wireframe\scanner.lua"]:417: in function `SaveProfessions'
[string "@BagSync\wireframe\events.lua"]:350: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>`

**Comment by agentschmitt** [comment]
this api has been changed: https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_TradeSkillUI.GetRecipeInfo

maybe fixed with changing this line
if (C_TradeSkillUI.GetRecipeInfo(recipeIDs[i], recipeData ))
to
recipeData = C_TradeSkillUI.GetRecipeInfo(recipeIDs[i], 1)
if recipeData then

but i am not sure for the recipeLevel, if 1 is correct but couldnt find an api to get the info

**Comment by Xruptor** [comment]
Thanks I'll look into it.
