### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pickaxe12** [Xruptor/BagSync#127]
Installed the Bagsync.  I need the tooltips for items and alts inventory. When installed Imlost control of mouse, menus and basically ui stopped working. Several buttons became un-clickable.
I use Baud Bag for all bag related stuff.
No lua codes or error messages.

**Comment by Xruptor** [comment]
If you use ElvUI by any chance, make sure you update it.  In terms of Baud Bag, make sure that is updated as well.

In order to determine what is going on, I need you to disable **ALL** addons **EXCEPT** BagSync.  **Only have BagSync working.**  Check to see if you still have the same issue with the standard default WOW bags.  Check if you see the BagSync information on the bank and in your tradeskill windows.  Also double check you have access to your mouse and such.

Please get back to me once you've done the step above. :smile

**Comment by Pickaxe12** [comment]
All my addons should be up to date. Disabling ElvUi fixed the issue tho. And I only disabled ElvUi.

**Comment by Pickaxe12** [comment]
Nevermind, my bad! 
Seemed like I missed an update for ElvUi. 
All is working fine now! 
Thank you for your fast reply and great work with this addon! <3

**Comment by Xruptor** [comment]
> Nevermind, my bad!
> Seemed like I missed an update for ElvUi.
> All is working fine now!
> Thank you for your fast reply and great work with this addon! <3

I figured it was ElvUI as that's been a common issue as of late.  Glad you were able to fix it.

**Comment by CosmicCleric** [comment]
https://github.com/pereira-a/MBB/issues/6

**Comment by CosmicCleric** [comment]
Realize this is closed, but wanted to leave this here for documentation reasons.

https://github.com/pereira-a/MBB/issues/6

So MBB was not seeing buttons that are fired off via 'OnMouseUp' events; [BagSync](https://github.com/Xruptor/BagSync) was one of these.

MBB was modified to find buttons using OnMouseUp, and once this was done, MBB found the BagSync button and added it to the consolidated view of addon buttons.

However, ElvUI was now also being seen, where it wasn't before, and when MBB worked in conjunction with ElvUI, the error occurs.

MBB was revered, so the trigger condition no longer happens in ElvUI.

There's some incompatibility with MBB interacting with the ElvUI code base.
