### ISSUE TITLE
Showing Reagant number...

### ISSUE THREAD

**Issue by Fabricatedhero** [Xruptor/BagSync#131]
It is showing reagent number for a character that does not have that item in its bag. Causing the totals to be off. I can email a screenshot if needed.

**Comment by Xruptor** [comment]
Could you possibly provide me with a screenshot.  Also, the BagSync.lua file from your SavedVariables folder would be great.  I can track it that way.  It's located under the following.

WOW Directory\_retail_\WTF\Account\{{YOUR ACCOUNT NAME}}\SavedVariables\BagSync.lua

You can drag and drop it here to attach it.

**Comment by Xruptor** [comment]
Oh lol and I also need the character name that is causing the issue with incorrect count and what not.

**Comment by Fabricatedhero** [comment]
Fhero is the one that does not have the reagant/item. Screenshot is from Macreive
![bagsync](https://user-images.githubusercontent.com/74896862/103972395-28ce0a00-512a-11eb-9ea0-30b44e95b00c.png)

Changed the extension as it wouldnt let me upload a lua
[BagSync.txt](https://github.com/Xruptor/BagSync/files/5785118/BagSync.txt)

**Comment by Xruptor** [comment]
> Fhero is the one that does not have the reagant/item. Screenshot is from Macreive
> ![bagsync](https://user-images.githubusercontent.com/74896862/103972395-28ce0a00-512a-11eb-9ea0-30b44e95b00c.png)
> 
> Changed the extension as it wouldnt let me upload a lua
> [BagSync.txt](https://github.com/Xruptor/BagSync/files/5785118/BagSync.txt)

Thanks for the response.  I'll take a look and see if I can reproduce the issue.

**Comment by Xruptor** [comment]
Can you do me a favor and login to Fhero and then check the bank.  I have a feeling I know what it is.  However I want to rule it out.  Otherwise, I'll continue to investigate it.

From what I'm seeing Shrouded Cloth is on WOWHead listed as item 173202
https://www.wowhead.com/item=173202/shrouded-cloth

According to BagSync.lua, Fhero should have 5 stacks.  4 stacks of 200 and 1 stack of 116. Totally 916 that is shown above.  In order to rule out what I think it is.  I need you to login to that character and check the bank again.  Let me know if it updates properly.  If it doesn't let me know as well.

**Comment by Xruptor** [comment]
I haven't heard back in several days now.  I'm assuming visiting the bank with the character in question fixed the issue.  In general when crafting items that consumes items from the Reagent bank, BagSync does not know what reagents were actually consumed. The only way for this data to be updated is to actually visit the bank.  There really is no way around this and there are built in limitations in the Blizzard WOW client.

Please see ticket #128 for further information.  Another user asked a similar question in ticket #130.  Unless there are any further questions, I will be closing this ticket.

**Comment by Fabricatedhero** [comment]
sorry and apologize haven't been able to get on due to RL stuff and to bring up a closed ticket. I did go back to the bank and still shows up as with reagent number. The character Fhero does not have these in the bank or bag.

**Comment by Xruptor** [comment]
> sorry and apologize haven't been able to get on due to RL stuff and to bring up a closed ticket. I did go back to the bank and still shows up as with reagent number. The character Fhero does not have these in the bank or bag.

Okay I reopened the ticket then.  Could you please take a screenshot of your reagent bank as Fhero.  I want to see the slot number so I can count them using your file.  It should give me an idea of what's going on.

**Comment by Fabricatedhero** [comment]
I double checked and i wasted your time. Thank you for the patience. It is correct now

**Comment by Xruptor** [comment]
No problem.  Like I mentioned above.  Unfortunately, BagSync cannot update the number of reagents used outside the bank during crafting.  The only way to update it, is visiting the bank.  This is something completely out of my control and a built in limitation of the WOW client.  Again see ticket #128  and #130 .

**Comment by Xruptor** [comment]
v14.9
-Finalized code that will calculate and predict the amount of items that were used while crafting from the Bank and ReagentBank and store it to the database.

-Prediction algorithm should be fairly accurate when consuming items from the Bank and ReagentBank when crafting.  However, it's not 100% foolproof.  It will definitely be 100% accurate once the player visits the bank though.  This is due to limitation imposed by Blizzard on the WOW client.

-Some code cleanup.
