### ISSUE TITLE
Minor QoL requests

### ISSUE THREAD

**Issue by silverhawke249** [Xruptor/BagSync#132]
1. Is it possible to make the key-bound windows toggle? Currently I have the Search window bound and being able to show/hide it with the same keybind would be great, since the only way to close it is by the X button
2. Similarly to above, perhaps allowing the Search window to be closed by hitting Escape.

Thanks!

**Comment by Xruptor** [comment]
I don't think this would be too cumbersome to add.  I'll take a look and see what I can do.

**Comment by silverhawke249** [comment]
awesome! can i add one more thing? would it be possible to have a keyword to search things belonging to a particular character? something like `@bag&char:Thrall`

**Comment by Xruptor** [comment]
> awesome! can i add one more thing? would it be possible to have a keyword to search things belonging to a particular character? something like `@bag&char:Thrall`

That may be a bit more problematic. Lets say you have multiple characters on several servers named Thrall within the same Battle.Net account.  When you do a character search for Thrall it would bring in all of them since it wouldn't know which one you are referring to.

Technically yes I can have it accept a realm as well.  But then that opens a localization can of worms that I don't really want to get into.  Things like how a person spells a server name vs how I'm stripping name spaces and storing it in the DB.  You would have compatibility mismatches. Hopefully I explained it well.  😄

**Comment by Xruptor** [comment]
I will be implementing the toggle using the bound keypress and the ability to close a window with ESC in next major patch.  I'm also considering adding a custom search or "advance search" window for BagSync to allow folks to select options on which characters to search on and where.  Using checkboxes and such.  That way they can do a search based on the criteria they selected.  It's something I'm considering, but I don't know when I will implement it.  So please keep that in mind.

**Comment by silverhawke249** [comment]
i definitely overlooked the "multiple characters with same name over several realm" possibility haha -- even if it's arguable that it's kind of useless info since you can't transfer items cross-realm (without character transfers), i'm not getting into that :P

but this sounds great! an interface for advanced search would be nice; i find myself looking at the addon's page to remind myself what keywords i can use -- though, not a problem i run into often. definitely looking forwards to the toggle/Esc update.

**Comment by Xruptor** [comment]
UPDATE: I have wrapped up the code for the Advanced Search option for BagSync and will be available in next major BagSync version update.

**Comment by silverhawke249** [comment]
awesome! looking forward to it :D

**Comment by Xruptor** [comment]
Its pushed live.  Enjoy. BagSync v14.8
