### ISSUE TITLE
Item count for bank items doesn't update when used in remote crafting

### ISSUE THREAD

**Issue by JoakimYsland** [Xruptor/BagSync#133]
Item count for bank items doesn't update when used in remote crafting, as in crafting with materials in the bank while not actually interacting with the bank.

**Comment by Xruptor** [comment]
This is working as intended. Unfortunately, Blizzard only allows addon authors to update Reagent data when a player visits a bank. Once you open the bank window, we can scan the Reagents as it's considered a special bank space. Outside of that we aren't able to update it and can't make predictions as to what item was removed from it when crafting. Bank, Auction, Void Bank, Reagents are all locations that must be visited in order for any data to be updated. This is the same for pretty much any addon that relies on scanning. It's just a built in limitation in the Blizzard code, sorry to say. 😢

Player bags though are updated in real time as that can be scanned at any point in time. Sorry if this isn't the news you were hoping for.

**Comment by Xruptor** [comment]
Please see previous bug reports filed with the same report.  #128 #130 #131

**Comment by JoakimYsland** [comment]
Ah, I suspected as much. Shame it's not possible. Sorry for the duplicate and thanks for the nice addon :)

**Comment by Xruptor** [comment]
v14.9
-Finalized code that will calculate and predict the amount of items that were used while crafting from the Bank and ReagentBank and store it to the database.

-Prediction algorithm should be fairly accurate when consuming items from the Bank and ReagentBank when crafting.  However, it's not 100% foolproof.  It will definitely be 100% accurate once the player visits the bank though.  This is due to limitation imposed by Blizzard on the WOW client.

-Some code cleanup.
