### ISSUE TITLE
Multi role lag

### ISSUE THREAD

**Issue by zkpjy** [Xruptor/BagSync#140]
Starting with version 12.0,When there are multiple characters, conduct item statistics. Sliding the mouse over the item will cause framp drop.
The problem seems to be tooltip.lua 416 lines.

**Comment by Xruptor** [comment]
I've tried this on several computers and I'm just not getting any framerate drop.  Can you give me an idea of how many characters you have?  I have quite a bit and I'm not getting a drop.  Remember that BagSync has to parse A LOT of item data on several characters.  That's a lot of data if you have quite a bit of toons.  Hundreds of thousands of items.  So keep that in mind.

I will be updating BagSync soon.  Let me know if you still get the issue and I'll have to look into it further.

**Comment by zkpjy** [comment]
There are 16 roles. (Before version 12.0, it was normal.)
[img]https://live.staticflickr.com/65535/51501958624_a9aa32b2fa_o.gif[/img]

**Comment by Xruptor** [comment]
> There are 16 roles. (Before version 12.0, it was normal.)
> [img][https://live.staticflickr.com/65535/51501958624_a9aa32b2fa_o.gif[/img]](https://live.staticflickr.com/65535/51501958624_a9aa32b2fa_o.gif%5B/img%5D)

Hmm lets see if I can debug this then.  Please provide me with your BagSync.lua file found under the following directory.  I'll try to load your BagSync data on my end and see if I can pinpoint what is causing it then.

Go to the following directory on your computer where your World of Warcraft installation is:
World of Warcraft\_retail_\WTF\Account\<<YOUR ACCOUNT NAME>>\SavedVariables

inside that folder is a file called **BagSync.lua**.  Please attach it to this ticket.  By either Dragging or Dropping the file when you type out your reply.  You can also click the "Attach files by dragging & dropping, selecting or pasting them." link below.

**Comment by zkpjy** [comment]
OK, thank you!
[BagSync.lua.txt](https://github.com/Xruptor/BagSync/files/7212223/BagSync.lua.txt)

**Comment by Xruptor** [comment]
> OK, thank you!
> [BagSync.lua.txt](https://github.com/Xruptor/BagSync/files/7212223/BagSync.lua.txt)

Thank you! I should be able to use this to see what's going on.  So give me some time to test out various things and see if I can pinpoint the issue.

**Comment by zkpjy** [comment]
^_^

**Comment by Xruptor** [comment]
I haven't had time to look over this yet until today.  Hopefully I can use the data to replicate the problem and pinpoint what is going on 😄

**Comment by Xruptor** [comment]
Okay I have located the issue and it's what I suspected.

You have the option to **"Display Battle.Net Account Characters"** -----> **enabled**. 

 If you notice this option is labeled as "_**(Not Recommended)**"_ for a reason. 😄   

![image](https://user-images.githubusercontent.com/202515/134808511-e9ed40e8-a9d3-4027-8414-3d25e5bab0dc.png)
 

Basically what is happening is that BagSync is going through **EVERY REALM** and **EVERY CHARACTER** searching **ALL** their **bags, auctions, banks, void, mailbox, etc...** for every _single one of your characters_.  Typically you want to only show data for characters on YOUR realm or CONNECTED REALM and not every character on your entire Battle.net account.

Why?  Because you really _can't share items between characters on different realms_.  Only account-bound items can be shared between characters on different realms.

This is why that option is labeled as **(Not Recommended)** since there is no real purpose in seeing item counts from toons on other servers.  The moment you turn this option off the FPS lag goes away.  I really and highly recommend you turn that option off. I looked at your data and that's A LOT of characters to go through on multiple realms.  There really isn't a need to see all those item data's for those toons.  If you can't share items between them on the character you a re logged in as.  The only thing I can think of is that you share items with people on THAT server when they ask?

There really isn't anything to fix for me here.  It's just a lot of data to parse at a given second when you hover over an item.  That's why the framerate dips 1 or 2 for a second.  I wish I had better news for you 😢 

I hope I explained that well!

**Comment by zkpjy** [comment]
Thank you, Yes.
But, Can the frame rate not drop when it is turned on?

**Comment by Repooc** [comment]
> Thank you, Yes.
> But, Can the frame rate not drop when it is turned on?

No that is why they have the warning there as there is a big performance hit...

**Comment by Xruptor** [comment]
> Thank you, Yes.
> But, Can the frame rate not drop when it is turned on?

Sadly no there isn't a way as @Repooc mentioned above,.  That option is labeled as "Not Recommended" for a reason.  It is just TOO much data for BagSync to process without causing a performance (lag/fps dro) hit on the client.  I explained that in my comment above.  I'm truly sorry and I wish there was something I could do, it's just too much data to parse within a second without causing a slight FPS drop.  I just suggest leaving this option off.  You really don't need to see the items for those characters as you can't trade with them.  Stick to characters on your server or connect realm servers.

**Comment by zkpjy** [comment]
In order to facilitate viewing, I really hope there is a perfect way.
Thank you very much for your answers.
