### ISSUE TITLE
Error at showing total currencys in a shop

### ISSUE THREAD

**Issue by rubenjurado** [Xruptor/BagSync#161]
When i put my mouse over a currency in a shop, it shows me how many i have, thats fine, but when showing me total currencys from all my characters, instead of using the currency i have my mouse on, its showing me the total currencys from the first item in the shop.

As showing in the capture (Sorry, image is in Spanish) you can see it says:

Total: 96
And a bit down it says i have 18,459 in my char, which its not true, i have 18,450 from the first currency in the shop, but not from the one i am looking at.
![Captura](https://user-images.githubusercontent.com/8775487/161746362-72af2e73-d429-45e1-8f2d-d722ba81ee7e.JPG)

**Comment by Xruptor** [comment]
That's very odd.  It should be showing the totals for the exact same currency.  Is that 96 accurate for your current character?  If it is then I'd need to see why the other ones aren't showing up properly.

**Comment by Xruptor** [comment]
It looks like it's grabbing the previous currency instead of the current one.  I'm going to attach a special BagSync here.  I need you to use this one and enable a new Debug option in the settings.

Please enable **"Display ItemID in tooltip"** and **"Display Source, ID and Debug Info in tooltip."**

Then hover over an item.  It should display in the tooltip the CurrencyID and the Debug Source.  I'm going to review your BagSync data right now but I need you to show me snapshots of this updated BagSync with debug info when hovering over items.

Here it is :)
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8428875/BagSync.zip)

**Comment by rubenjurado** [comment]
Sure, here is 2 captures 

![Captura](https://user-images.githubusercontent.com/8775487/162027179-26dd04f3-4243-4b62-bad5-7154860564b1.JPG)
![Captura2](https://user-images.githubusercontent.com/8775487/162027185-6e825117-91d3-4b80-a13b-1363b5603d05.JPG)

**Comment by Xruptor** [comment]
Thanks for the response.  I'll take a look and do a comparison. I think the index for the currency has changed in an update.  Let me review your data and see if I can fix it :)  I kind of figured it was SetMerchantCostItem.

**Comment by Xruptor** [comment]
Okay I'm going to need your help again since I don't have WOW installed ;)

Download this debug version of BagSync.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8444451/BagSync.zip)

It will print to your chatframe some debug info that I need to see.  What I need you to do is to take screenshots from each currency starting from the first one on the list and then while going right and back down to the left again.  Do it for each one.  Especially for the ones that have more than one currency in it.  Like the Ominous Shard of Zed which requires two currencies.  I need to see if the currency being pulled is in the correct order.  Which I think is the problem here.  In order to do this, I need to see it in the exact proper order from top to bottom to make sure it's grabbing the currency correctly.

Again this will print stuff in your chatbox :)  It should be separated each time by "----"

**Comment by Xruptor** [comment]
Whoops I made a mistake. I meant this BagSync. XD
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8444499/BagSync.zip)

**Comment by rubenjurado** [comment]
Here is the image of all items from "Vision of Bonesmith Heirmir" from Korthia

Items who have 2 currency prices like "Ominous Shard of Zed" only print in chat when hover Stygian Ember, doesn't print nothing while hovering the shards, guess cuz they are just items

Hope it helps, all items in the captures are in order from the shop

![1](https://user-images.githubusercontent.com/8775487/162266211-d9381f59-7718-4784-808a-51cf22e20f7c.JPG)
![2](https://user-images.githubusercontent.com/8775487/162266215-2a041202-1c0d-4e6f-9613-7997e2fc3cd0.JPG)
![3](https://user-images.githubusercontent.com/8775487/162266218-9cfa5eed-94ce-4739-ae78-dd27a7378297.JPG)

**Comment by Xruptor** [comment]
Thanks let me review and see if I can spot the pattern. :)  I may have to have you debug one more time though.  I'll let you know!  This is great though and really helps out.

**Comment by Xruptor** [comment]
I think I figured it out.  Please try the version below. It should work with all the currencies, including the shards that didn't print out debug info.  Please let me know if it works and provide screenshots if it does :)  Don't forget to keep the ItemID and Debug options turned on so the info shows up on the toolips!

[BagSync.zip](https://github.com/Xruptor/BagSync/files/8447214/BagSync.zip)

**Comment by rubenjurado** [comment]
Hey, looks like the tooltip isnt showing nothing, and its not printing nothing in chat, ast least for currecys from shop.

I have enabled ItemID and Debug, but the addon its not working for currencys, just works for items in bag 
![Captura](https://user-images.githubusercontent.com/8775487/162394253-af84ebeb-9555-4872-9533-98c37f42fcf0.JPG)

**Comment by Xruptor** [comment]
really? Huh, that's odd it should be working.  I'm going to have to add Debug stuff to print to see what's going on.  I could have sworn I fixed the issue.  Now I'm baffled lol. XD  Thanks for your help btw.  Let me put together a Debug version.

**Comment by Xruptor** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8451935/BagSync.zip)

That version should print out information in chat.  It may even work properly.  I need you to also check your characters personal Currency Window and see if it works there as well.  Let me know how things go :)

**Comment by rubenjurado** [comment]
Now looks like its showing the correct currency, but just for some characters in the total count, and ignoring other characters haha (For example the first image shows only 3 characters, even when i refreshed data from the rest chars, and for Soul Ash in total doesn't show any character, but in my demon hunter i have a bit from that currency )

Currencys from the currency tab doesn't show nothing in tooltip btw

![1](https://user-images.githubusercontent.com/8775487/162441937-66a5e3ef-d79c-4652-b0b3-9bd6d62e5ff2.JPG)
![2](https://user-images.githubusercontent.com/8775487/162441938-f4ba900b-b751-4794-8b9c-982329bdb567.JPG)
![3](https://user-images.githubusercontent.com/8775487/162442919-b4baefee-d4b7-48d5-877f-fe9e0512a95b.JPG)
![4](https://user-images.githubusercontent.com/8775487/162442922-37feb885-2f4d-4f8a-b8e0-df48d291ba20.JPG)
![5](https://user-images.githubusercontent.com/8775487/162442923-0e988080-ebbd-4b8c-9d25-be1f82b2a1f3.JPG)

**Comment by Xruptor** [comment]
Okay I think the spotted the error.  B: should not be returning "nil" and it should not be going in C unless it's a last resort.  GetCurrencyID is returning 1906:0 when it should be returning 1906.  Which means in a patch they added another number to the currencyID string.  I just need to strip it.  It should fix it.  Could explain why all this wasn't working in the first place.

**Comment by rubenjurado** [comment]
Nice to see it helps haha

**Comment by Xruptor** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/8453559/BagSync.zip)

Okay hopefully this debug version works properly. Please check the Currencies including the Shard.  I need to make sure the item shark works even if it isn't an actual currency.  It should print out as "D:" if it works.  Also I think I fixed the Currency/Token window, so try that again :)

I think the other characters weren't showing because it wasn't properly linking the currencies.

**Comment by rubenjurado** [comment]
Looks like currencys are working fine now, even from the currency tab!
Shards are not printing nothing in chat yet, so couldn't test it

![1](https://user-images.githubusercontent.com/8775487/162487280-88591404-907f-45e8-826b-880c16c96ce6.JPG)
![2](https://user-images.githubusercontent.com/8775487/162487282-33adc72a-8c4d-4717-87cb-dfbafe70e01d.JPG)
![3](https://user-images.githubusercontent.com/8775487/162487284-1b74a605-74fb-47f9-9075-59ee62026d8a.JPG)
![4](https://user-images.githubusercontent.com/8775487/162487286-eec103f3-ca9a-41a6-b69b-feec3890389a.JPG)
![5](https://user-images.githubusercontent.com/8775487/162487287-8d3507eb-ea6c-4786-8f33-8b643dcee183.JPG)
![6](https://user-images.githubusercontent.com/8775487/162487289-50e6a848-cb10-475f-bec1-dc357666873b.jpg)
![7](https://user-images.githubusercontent.com/8775487/162487290-2d20cde0-e654-4aa1-b13f-20b948d4c670.JPG)
![8](https://user-images.githubusercontent.com/8775487/162487293-c2b1292b-0430-49b1-8557-e9355c77d619.jpg)

**Comment by Xruptor** [comment]
Well that's great 😄 !  Solved the currency issue now got to figure out why that shard isn't working.  It's using another method entirely according to the debug. OnTooltipSetItem.

I don't think you even have any of these shards.  It's displaying the ItemID correctly as 187076.
https://www.wowhead.com/item=187076/shard-of-oth

After reviewing your BagSync.lua data.  None of your characters have itemID 187076 anywhere.  Which is why that tooltip is empty.  Unless I'm missing something it should be working properly then?  Just let me know :)

**Comment by rubenjurado** [comment]
Yeah sadly i dont have any shard since i didnt play the last patch. Maybe its working fine haha.

I Will see  if i can get one to test it

**Comment by rubenjurado** [comment]
Okay, i looted fragments from korthia chest and i think it`s working fine !
![1](https://user-images.githubusercontent.com/8775487/162567289-5cfb49de-44b1-4554-9df4-1982d7f2c840.PNG)

**Comment by Xruptor** [comment]
> Okay, i looted fragments from korthia chest and i think it`s working fine ! ![1](https://user-images.githubusercontent.com/8775487/162567289-5cfb49de-44b1-4554-9df4-1982d7f2c840.PNG)

That's great news!  😃 What I will do is remove the chat print debug stuff and keep all the changes including the new debug option for the tooltips :)  Then I'll push a new version right now on CurseForge and WOWInterface.  So keep an eye out for the new update!

Thank you so much for your help!  You've been absolutely wonderful and I couldn't have figured this out without your help. 👍
