### ISSUE TITLE
Professions not displaying in window

### ISSUE THREAD

**Issue by MZelko82** [Xruptor/BagSync#172]
As per the image, the professions window is empty for me. As a check, the currency one works fine.

![BagSync_7_6_22](https://user-images.githubusercontent.com/73236090/172298894-b1280ffd-2d39-4dfb-84cc-49cf2bd2a257.png)

**Comment by Xruptor** [comment]
Hey there is this problem still happening?  Have you made sure to open all your professions at least once?  It needs to scan everything.  Please let me know and I'll work with you to solve the issue.

**Comment by MZelko82** [comment]
Hey thanks for the quick update. I did not realise I needed to open each profession's recipes tab, but that does seem to have fixed the problem.

Thanks again!

**Comment by Xruptor** [comment]
> Hey thanks for the quick update. I did not realise I needed to open each profession's recipes tab, but that does seem to have fixed the problem.
> 
> Thanks again!

Sure thing! Sadly addons aren't able to retrieve ANY profession/crafting information until a player opens up the professions/tradeskill windows.  Then the client receives all the data corresponding to that.  That is why I can only scan when a player opens up the tradeskill windows.  Because otherwise there is no data to scan with the current changes to the WOW code.  Hope this helps!
