### ISSUE TITLE
Suggestion, Shows account gold when mousing over gold in your bags?

### ISSUE THREAD

**Issue by Donovan4893** [Xruptor/BagSync#187]
I know you can view your account gold by doing /bgs gold but would it be possible to display that information when your mouse over the gold at the bottom of your bag?

**Comment by Xruptor** [comment]
Someone had asked this before I think.  If I recall the reason I didn't add it was because I would have to add support for every Bag addon out there.  Which was just too crazy for me.  If I restrict it to just the Blizzard bags people will complain and want support for their bag mod.  I'll give it some though and look at the currency code.

**Comment by Xruptor** [comment]
I've reviewed this enhancement and at the moment I don't think I will implement it.  I did get it to work with the default bags but people are going to complain and want it to work with other bag addons like Bagnon, AdiBags, etc..  Which will take additional time and coding to add compatibility for.  It's just easier not to implement it and leave it the way it is.  I hope you understand 😄
