### ISSUE TITLE
Issue: Auto Focus Search Window Option "Pastes" Keybind

### ISSUE THREAD

**Issue by Jdaddy0007** [Xruptor/BagSync#200]
When you have a keybind to open the search window AND the option to focus the search window, the keybind will be placed into the EditBox (see images).  Requiring a backspace every time the keybind is used.
https://imgur.com/a/yIRInVr

I understand this is a recent feature: #178 / https://github.com/Xruptor/BagSync/pull/181
And I love it!

Thank you!

**Comment by Xruptor** [comment]
OMG LOL... that's a hilarious bug.  Let me see if I can replicate it.

**Comment by Jdaddy0007** [comment]
> OMG LOL... that's a hilarious bug. Let me see if I can replicate it.
😝 ❤️

**Comment by Xruptor** [comment]
Okay yes I see what it is.  The Search Bar is automatically grabbing the input of the keypress because technically it's held down when the window opens.  This also happens if you hold down the keybind button, it will just spam it in the search bar.  In order to alleviate this a bit, I've added a short half second delay before the search bar grabs focus.  This will NOT however stop people that just hold the button down LOL.  But it should help.  No way really around this for a search bar that has focus waiting for text you know 😄

**Comment by Jdaddy0007** [comment]
Thank you! So much! Greatly appreciate the rapid turn around!
