### ISSUE TITLE
[retail] Guild bank scan when two guilds have the same name

### ISSUE THREAD

**Issue by leemitchell25** [Xruptor/BagSync#213]
Hi. I've run into an issue.

I play both Horde and Alliance and am in a guild on each faction. The problem is that the Guilds have the exact same name and share realms. (See attached image)

![image](https://user-images.githubusercontent.com/49726970/205522638-fcfb7cb1-652b-4e19-88ba-56f139fc74a1.png)

The Alliance version of the Guild is on Cairne, the Horde version on Perenolde.

The problem is that when I do the Guild Bank scan the data is being dumped into one Guild profile ... and it's only showing for the Horde. (I'm sure if I had started scanning with the Alliance guild it would show up there instead, and the Horde bank would dump into it).

Is it possible to add a Realm identifier to the Guild Bank data so as to separate the two internally (eg. Guild-Perenolde, Guild-Cairne),?.

Or if you can think of something else that will fix it that would be great.

Thanks in advance. :)

**Comment by Xruptor** [comment]
This will be quite difficult to implement.  The original reason I had them combined is that people complained about having multiple guilds with same names showing up.  So I combined them within the same realmkey (for the combined worlds).  I could technically separate them but then we have another issue.  You will have two exact guilds show up in the tooltip.  How would you know which is why?  You'd have to enable "Show Realm Names" but that puts it for everything and it may annoy you to see the realm names for characters rather than guilds.  Basically it's a lot of juggling for an issue I didn't anticipate.  I'm sure there is a solution but I'd have to weigh everything.  Especially since there is always someone somewhere that will complain about a change I make XD.  Though right now the simplest solution would be to add an option that disables the merging.  Though like I said once again it would show double guild names with no identifier to let you know which is why.

If I were to attach the realms to the guilds, then  it would show twice if someone enabled the "show realm names" given how they are processed.  See the complications lol.  I'll give it some thought.

**Comment by leemitchell25** [comment]
Had a thought ... at the moment I have BagSync set to not display Cross Realm characters,

I activated the Cross Realm functionality and I could see for an item:

`[XR-Perenolde] Nevermind the Murlocs       Guild: 10`

This is the total for both realms as you've said is how it currently works. But would it be possible to display:

`Nevermind the Murlocs                                Guild: 2`

`[XR-Perenolde] Nevermind the Murlocs       Guild: 8`

That way if you have Cross Realm disabled only your current realm is displayed, but if you have it turned on it displays everything.

My assumption here is that you're storing the realm name with the item data but if not I can see it being difficult to split apart Hmm. Well it was an idea, hopefully it sparks something for ya. :D

**Comment by Xruptor** [comment]
That would work technically as internally only one guild DB entry is made per combined realmKey.  So separating the data would require a new entry in the DB altogether for the other guild.  That's part of the problem in trying to incorporate this.  I just never really anticipated someone creating multiple guilds with the same name within the same Connected Realms.  So really have to give it some thought on how to implement this without breaking everything.

**Comment by Xruptor** [comment]
[BagSync.zip](https://github.com/Xruptor/BagSync/files/10181954/BagSync.zip)

Please try this testing version of BagSync.  Let me know if it works for you.  Because I changed how guilds are stored, it will remove your old guild data.  So you will have to scan them again with your characters.  Remember that realm names will not display unless you turn it on.

Let me know if this works for you.

**Comment by leemitchell25** [comment]
Looks great! Thank you so much!! :D 

_Possible minor improvement: Would it be possible to list the guilds in the same grouping as the character realm data. Might help people realize that the listed guild is in the same realm as those characters without turning on the realm names._

![image](https://user-images.githubusercontent.com/49726970/206562309-eb9abcf4-ad2f-439c-91a5-d709be5d51a9.png)

**Comment by Xruptor** [comment]
> Looks great! Thank you so much!! :D
> 
> _Possible minor improvement: Would it be possible to list the guilds in the same grouping as the character realm data. Might help people realize that the listed guild is in the same realm as those characters if they don't turn on the realm names._
> 
> UPDATE: Forgot to test the profile list. I just did it and the guilds are showing properly in each realm. :D
> 
> ![image](https://user-images.githubusercontent.com/49726970/206562309-eb9abcf4-ad2f-439c-91a5-d709be5d51a9.png)


Okay okay good.  So everything works.  Including the realm names if turned on.

**Comment by leemitchell25** [comment]
Yep, the third image has realm names and cross-realm turned on. :)

Totally understand about the sorting, like I said it would be a minor improvement. All guilds at the bottom works too. :)

Thanks again. :D

**Comment by Xruptor** [comment]
Perhaps I'll add a minor option to sort by realm and one to show realms on guilds only.  :) I'll take a look into it, perhaps I can mix it with the logic of other options.  I'll keep you posted.

**Comment by Xruptor** [comment]
Guilds will now be sorted with their respected realms.  Please note in order to see the guild realm tags, you still have to enable it.  I decided against putting an option to only show Realms for guilds.  Honestly, if a person has guilds on other servers, they can just easily enable realm server tags.  It's either all or nothing.  I can't begin to be nitpicky with the options.  It leads to a whole mess later on programming wise with the logic.

**Comment by Xruptor** [comment]
https://github.com/Xruptor/BagSync/commit/73e99a94415233834c47c9e9eebaff6bc024fc2a

**Comment by Xruptor** [comment]
Pushed a live update.  You will need to remove the Debug version I gave you and use the live version with all the fixes.
