### ISSUE TITLE
Retail : Anoying battlepet tooltip when we have battlepet in bank

### ISSUE THREAD

**Issue by Hermonii** [Xruptor/BagSync#217]
Hi, there a screen that show the problem. Easier to explain it.
![image](https://user-images.githubusercontent.com/118864327/206628997-9b4aebd4-9b4c-4f1b-917b-9b46b376f69f.png)

BagSync is the only add on activated during this test.
I just caged a battle pet, added it into this old guildbank. And the issue dont always appear but really really often when i mouseover any item I have this tooltip hiding the other one.

On this screen, my mouse was on the blue potion and that show the tooltip from the battlepet.

Hoping you'll find why that do that and fix it^^

**Comment by Xruptor** [comment]
This may be a server delay issue that is beyond my control.  I will look into it.  Just so that you know, working with Battle Pets and the Guild Bank is a total nightmare.  Blizzard didn't make it easy for addon authors to work with the code and the battle pets in ONLY the guild bank.  Everywhere else is fine.  Please read the F.A.Q entry in the BagSync addon all the way at the bottom for further details.

I'll see if I can reproduce this issue.
