### ISSUE TITLE
Retail: Sometimes items (in guild bank/bank) do not get picked up by BagSync and need multiple logins to do so

### ISSUE THREAD

**Issue by HausmeistaHausmeista** [Xruptor/BagSync#220]
As I was missing items in the tooltip and started to investigate. I noticed that sometimes new items do not get picked up by BagSync and need multiple logins to do so. I haven't been able to 100% reproduce it, but the best way to do it, is the following:
1.) Either create a new character or remove an old one from BagSync
2.) Disable all addons, log in and place at least one item into the bank and if you are in a guild, then into the guild bank as well
3.) Enable BagSync and do not open any bank
4.) Log out
5.) Log in
6.) Visit the bank / guild bank
7.) Wait like 30 seconds whilst having the (guild) bank open
8.) Mouse-over the item in the bank and see if it is listed in the tooltip
9.) Sometimes it is, sometimes not. If not, log out and you'll see that the item is also not in the BagSync.lua in \SavedVariables
10.) Log back in, open bank again, wait and see if the item is shown in the tooltip 
11.) If not, repeat logging out and back in until it does, which happens normaly on the second login, but can take up to five (which was the most for me in my tests)

BugGrabber/BugSack stays quiet during all this.
Tested with version 18.1.

Thank you very much for this AWESOME addon and all the time you've already invested in it. I have just discovered it recently as my old addon setup broke with Dragonflight, but it quickly jumped into my personal top 5 of addons. :)

EDIT: Added version used during my tests.

**Comment by Xruptor** [comment]
**Please try the newest version I just released and see if that helps.**

What you are describing to me sounds like some sort of server delay in scanning.  I don't exactly have this issue on my end but it's worth investigating.

I will need you to use the new BagSync Debug option.
Type `/bgs debug`

Click on `"Enable Debug"`

Make sure that DEBUG, INFO, TRACE is enabled.  Now visit a bank and it should show you logging information if the bank and guild is bring processed.  Please share that information with me here.  If I need to, I will add even more debugging lines.  But in general it should be storing the data.  The only thing I can think of is somehow the client isn't saving the BagSyncDB sometimes when you exit.

**Comment by Xruptor** [comment]
It seems to me that the item is being processed and stored.  You are testing it on ItemID 168802.  (https://www.wowhead.com/item=168802)

I'm still a bit confused on what exactly is going on.  However, I'll see if I can trace the issue.  Please if possible use Character names to describe things.  It gets difficult for me to try to understand which and whom you are referring to when you say "character".  :)

1. You login to your character **Testchar** that only has items in the bank? Nothing in the bags.
2. You go to the bank or guild bank and open it on **Testchar**.
3. You hover over an item in the bank.  It displays **Butterkeks** has having 168802 (https://www.wowhead.com/item=168802).  But not **Testchar** right?
4. You logout **Testchar**
5. You login **Testchar**
6. It now shows that both **Testchar** and  **Butterkeks* have item 168802 (https://www.wowhead.com/item=168802)

> [15:08:37]: [Tooltip]: ColorizeUnit,  Testchar
> [15:08:37]: [Tooltip]: ColorizeUnit, [Pozzo dell'Eternità] Butterkeks

You need to be extremely specific when trying to reproduce the issue.  Using exact things you are doing and with character names and such.  Otherwise it's very difficult for me to follow what you are trying to describe.

If you can give me a extremely specific step by step process of what you are doing including interaction with bags that would be helpful.  You seem to have Crossrealms XR enabled BTW.  So I think I know what is going on but I need to verify a few things.  Please click on that "Iterate Units" button and provide me those details too.  Thanks.

**Comment by Xruptor** [comment]
It seems to me that the item is being processed and stored.  You are testing it on ItemID 168802.  (https://www.wowhead.com/item=168802)

I'm still a bit confused on what exactly is going on.  However, I'll see if I can trace the issue.  Please if possible use Character names to describe things.  It gets difficult for me to try to understand which and whom you are referring to when you say "character".  :)

1. You login to your character **Testchar** that only has items in the bank? Nothing in the bags.
2. You go to the bank or guild bank and open it on **Testchar**.
3. You hover over an item in the bank.  It displays **Butterkeks** has having 168802 (https://www.wowhead.com/item=168802).  But not **Testchar** right?
4. You logout **Testchar**
5. You login **Testchar**
6. It now shows that both **Testchar** and  **Butterkeks* have item 168802 (https://www.wowhead.com/item=168802)

> [15:08:37]: [Tooltip]: ColorizeUnit,  Testchar
> [15:08:37]: [Tooltip]: ColorizeUnit, [Pozzo dell'Eternità] Butterkeks

You need to be extremely specific when trying to reproduce the issue.  Using exact things you are doing and with character names and such.  Otherwise it's very difficult for me to follow what you are trying to describe.

If you can give me a extremely specific step by step process of what you are doing including interaction with bags that would be helpful.  You seem to have Crossrealms XR enabled BTW.  So I think I know what is going on but I need to verify a few things.  Please click on that "Iterate Units" button and provide me those details too.  Thanks.

**Comment by Xruptor** [comment]
I'm currently looking into this.  I will see if I can replicate the issue.  I have noticed an issue with schematics/patterns not being passed properly.  So it could be related.

**Comment by Xruptor** [comment]
It's okay don't worry.  I'll try to work with what you have provided me thanks.  If I need something else I'll let you know.

**Comment by Xruptor** [comment]
Just to make sure, so that I'm focusing just on the issue in the code.  This is **ONLY** when dealing with items the Bank and Guildbank right?  It has NOTHING to do with Inventory bags and such?

**Comment by Xruptor** [comment]
I cannot reproduce this problem at all. I've tried several different methods and various characters and every single one scans the bank and guildbank just fine.  When I hover over the item in the bank,  it displays the correct information.  Meaning that the (https://www.wowhead.com/item=5956/blacksmith-hammer) Blacksmith Hammer is showing up for both my bags and my bank.  I just don't know what else could be going wrong on your end.  If you can make a video that would be fantastic as like I said I cannot seem to reproduce this issue.

Try this new version of BagSync.  I added extra debugging for the bags and such.  You will need to enable "FINE" in the debug window.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/10201003/BagSync.zip)

**I created a testing character on RETAIL.**  Not sure if you are playing on WOTLK or Classic.

1. Login to my testing character called **Hathon**.
2. I have on this chacter 3 **Blacksmith Hammer** in the bags and 4 **Blacksmith Hammer** in the bank.
3. I go to **BagSync Profiles** and delete the profile for **Hathon**.
4. I logout
5. I login again
6. Hover over the **Blacksmith Hammer** in my bags and it shows I have 3 in my bags.  None in the bank.
7. I open the Bank.
8. I hover over the **Blacksmith Hammer** in the bank and it shows that I have 3 in my bags and 4 in my bank.  So the information is being displayed properly.

I tried several different login/logout and deleting of profiles (even on another character I made temporarily).  Nothing I do seems to replicate the issue you are getting.  My stuff just scans properly when opening the bank and guild bank.  See if your friend has the same issue.

**Comment by Xruptor** [comment]
Easiest solution for video would be to put it on youtube and set it to private.  Then just share the link here.

In terms of what you wrote.  The only thing I can think of is somehow, someway, and in some fashion.  The event that Blizzard sends to trigger a bank scan is not firing sometimes for you.  Which makes no sense at all.  🤣 So lets try adding a few debug lines to those events and see if we can figure it out.

**Comment by Xruptor** [comment]
I will figure this out if it's the last thing I do. XD

**Comment by Xruptor** [comment]
Okay so lets try something different.  Use this version of BagSync.  I added additional debugging stuff.  _(Hopefully you know how to manually install addons.)_
[BagSync.zip](https://github.com/Xruptor/BagSync/files/10202272/BagSync.zip)

P.S: I added a new "Clear" button for the debug screen to clear the bagsync debug log screen.


1. Open up BagSync Debug
2. Make sure that only **DEBUG** and **INFO** is checked.
3. Enable BagSync Debug and open the Bank window.
4. Close the Bank Window.

If a successful scan has been done to the **Bank** on **Retail**.  It should look like this.

```
[08:16:03]: [Unit]: PLAYER_INTERACTION_MANAGER_FRAME_SHOW, 8
[08:16:03]: [Events]: PLAYER_INTERACTION_MANAGER_FRAME_SHOW, 8
[08:16:03]: [Scanner]: SaveBank, nil, true
[08:16:03]: [Scanner]: SaveBag, bank, -1
[08:16:03]: [Scanner]: SaveBag, bank, 6
[08:16:03]: [Scanner]: SaveBag, bank, 7
[08:16:03]: [Scanner]: SaveBag, bank, 8
[08:16:03]: [Scanner]: SaveBag, bank, 9
[08:16:03]: [Scanner]: SaveBag, bank, 10
[08:16:03]: [Scanner]: SaveBag, bank, 11
[08:16:03]: [Scanner]: SaveBag, bank, 12
[08:16:03]: [Scanner]: SaveReagents, true
[08:16:05]: [Unit]: PLAYER_INTERACTION_MANAGER_FRAME_HIDE, 8
[08:16:05]: [Events]: PLAYER_INTERACTION_MANAGER_FRAME_HIDE, 8
```

1. Unit should show PLAYER_INTERACTION_MANAGER_FRAME_SHOW as frame 8, which is the Bank
2. Events should do the same thing as above.
3. Scanner should now SaveBank with the second option being **true**.
4. Scanner will save each individual bag found in the bank -1 to 12.
5. If you have Reagents unlocked, it will scan that as well with the first option being **true**.
6. When you close the Bank the PLAYER_INTERACTION_MANAGER_FRAME_HIDE should fire for Units and Event.  With frame number 8.

That is the correct process for saving stuff at the bank.  If the above is NOT happening when you visit a bank.  Then something is stalling the process.  That is why I added additional debug lines.  We need to see why the function calls are not being triggered.

Let me take a look at your video :)  Remember to use the BagSync I provided above.

**Comment by Xruptor** [comment]
I did get the response.  Thanks for testing it out and getting back to me.  **Please file a ticket for the other issue with the Reagent bags if you encounter anything.**  Keep in mind server delays and such when doing tests.
