### ISSUE TITLE
Plans, Patterns, Schematics do not show up in the tooltip

### ISSUE THREAD

**Issue by HausmeistaHausmeista** [Xruptor/BagSync#221]
I have found an old ticket where several issues with professions have been listed, but it seemed to be about other stuff, is already closed and you haven't mentioned anything regarding works as designed or being unfixable, I decided to open this one. :)

If you have any Plans, Patterns, Schematics, etc in your bags/banks, the owner/place of storage isn't shown in the tooltip. If you search for the itemID in the BagSync.lua in \SavedVariables, it is in there. And if you search for the item in the BagSync Search Window, it is also found. But as it doesn't list where it is, trying to actually find it can be pretty hard if you have a few chars. :)

Tested with version 18.2

**Comment by Xruptor** [comment]
Can you give me some examples of these Plans, Patterns, Schematics.  So I can try it for myself?

**Comment by Xruptor** [comment]
Thank you, I'll take a look.

**Comment by Xruptor** [comment]
I have identified the issue.  It looks like Blizzard is returning the crafted item ID instead of the pattern/schematic ItemID in it's new Tooltip Processing API functions they released in Dragonflight 10.0.  That is why it isn't working.  It's looking for the crafting item rather then the pattern recipe itself.  I've made some modifications to check for this and it seems to be working.
