### ISSUE TITLE
"Display Battle.Net Account Characters" makes server appear in tooltip for logged in character on certain realms

### ISSUE THREAD

**Issue by HausmeistaHausmeista** [Xruptor/BagSync#225]
Activating **Display Battle.Net Account Characters** leads to the display of the realm for the logged in character if the character is on very few selected realms.

**Display Battle.Net Account Characters** off
![WoWScrnShot_121222_194911](https://user-images.githubusercontent.com/118524600/207130216-c0f0c4cf-5679-4356-bd29-980ef12da212.jpg)

**Display Battle.Net Account Characters** on
![WoWScrnShot_121222_195016](https://user-images.githubusercontent.com/118524600/207130234-58309b5f-40c9-4152-9931-05a268082885.jpg)

Maybe it has something to do with _Der Rat von Dalaran_ being an RP realm and that the RP is omitted in certain situations due to overall length of servername.
Or it's because of the realm name consisting of more than three words as the same happens for characters on the _Culte de la Rive noire_ server. Which is also a RP server.
Or it is something completely different. :)

Can you take a look at this issue? Thank you very much

**Comment by Xruptor** [comment]
I suppose we can do some debug checks to see if I can figure out what you are referring to.  I still think it's because in the blizzard code it's being returned as connected and thus the BNET tag is given regardless if they are on the same server.  If anything it's a fluke on their end.

But lets check for it anyways :)

[BagSync.zip](https://github.com/Xruptor/BagSync/files/10218305/BagSync.zip)

Use that BagSync.  Turn on DEBUG, INFO and WARN.  Hover over the items on both characters.  Please put out the printout for just the tooltip stuff here for each character.  I need to see the ColorizedUnit and ColorizedUnit returns as well as a few other things.

**Comment by Xruptor** [comment]
> [Data]: IterateUnits, nil, nil
> [Tooltip]: ColorizeUnit, [BN Der Rat von Dalaran]  Leialeialeia, Der Rat von Dalaran, false, false, Der Rat von Dalaran
> [Tooltip]: ColorizeUnit [Realm], Der Rat von Dalaran, DerRatvonDalaran
> [Tooltip]: ColorizeUnit, [BN Der Rat von Dalaran] Ghghghghghgh, Der Rat von Dalaran, false, false, Der Rat von Dalaran
> [Tooltip]: ColorizeUnit [Realm], Der Rat von Dalaran, DerRatvonDalaran
> [Tooltip]: ColorizeUnit, [BN Blackhand] Xoxoxoxoxo, Blackhand, false, false, Der Rat von Dalaran
> [Tooltip]: ColorizeUnit [Realm], Der Rat von Dalaran, DerRatvonDalaran
> [Tooltip]: TallyUnits, table: 00000217281600F0, 3300, 3300, OnTooltipSetItem, nil, 3

For some reason, **Der Rat von Dalaran** is not being returned as a connected realm by the server.  Otherwise the first true/false variable after the name would be true.

> [Tooltip]: ColorizeUnit, [BN Der Rat von Dalaran]  Leialeialeia, Der Rat von Dalaran, **false**, false, Der Rat von Dalaran

According to https://wowpedia.fandom.com/wiki/API_GetAutoCompleteRealms  **Der Rat von Dalaran** should be a connected realm.

Lets see if that is true from the server.  Load this version of BagSync.  I added another Debug line.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/10227788/BagSync.zip)

Make sure **DEBUG** is enabled.  Login to the **Der Rat von Dalaran** server.  You are looking for the  **[Data]: RealmKey** line in the debug.

**Comment by Xruptor** [comment]
> Here's the data..
> 
> `[Data]: RealmKey, Der Mithrilorden;Der Ratvon Dalaran;Die Nachtwache;Forscherliga;Todeswache;Zirkeldes Cenarius`
> 
> I assume it has to do something with the blanks?

I'd have to check why that is being returned that way by the server.  It would explain why it's not working as it's not matching the same exactly.

**Comment by Xruptor** [comment]
Implemented some realm name checks to double check for situations like these.  Please try this version.

[BagSync.zip](https://github.com/Xruptor/BagSync/files/10240710/BagSync.zip)

**Comment by Xruptor** [comment]
> Thank you very much again for all your hard work! I tested all the servers having issues in the past and it worked for all of them now. :) Also tested a few "normal" servers and could not detect any issues. 👍 👍

Oh good! 😄 I'm glad it worked.  Thanks for the patience and time to work with me to resolve these tickets.

**Comment by Xruptor** [comment]
You as well Happy Holidays! 🎁🎄
