### ISSUE TITLE
coloring

### ISSUE THREAD

**Issue by blecaplol** [Xruptor/BagSync#234]
hi i went over to /bgs config to see if i can edit the class color when i hover my gold in the bag but its only showing 1 color despite of class. would be nice if this is change or something. like bagbrother it is in class color. thx!

**Comment by Xruptor** [comment]
I don't think I understand the request?  What exactly do you mean by class color when hover over your gold?  Whatever it is, is only showing 1 class color?  Can you provide me more details and perhaps a screenshot or something to what you are requesting?  Otherwise I have no idea what class color has to do with gold hehe.  😄   There is a gold display in BagSync if that's what you are talking about.  You can do **/bgs gold** or **/bgs money**.  If you enable class colors it works for that too.  If that's not what you are referring to, you will need to be a bit more specific.

**Comment by blecaplol** [comment]
hey man sorry i thought it was bagsync :p but it is actually arkinventory.

**Comment by blecaplol** [comment]
hey man sorry i thought it was bagsync :p but it is actually arkinventory.
