### ISSUE TITLE
Request: See Gold Across Characters by Hovering Over Backpack Gold

### ISSUE THREAD

**Issue by Zaef** [Xruptor/BagSync#249]
Hi! I was wondering if there was a way to enable a popup display of Gold across characters when hovering over the gold on your backpack (popup as in like how the tooltips for an item show counts of that item on other characters). I know about the /bgs gold command, but couldn't see an option to enable a hover display. Thanks!

**Comment by Xruptor** [comment]
Hey there!  Thanks for reaching out! :)

This request is asked quite frequently actually.  Unfortunately it would be difficult for me to implement something like this.  I would have to add support to **every bag addon out there**.  Since each one handles their gold displays differently, it would be a constant struggle to keep this code updated to ensure compatibility.  Since BagSync isn't itself a bag addon, it would require me to hook/grab into the code used by the bag addons to display the tooltip.  Due to how some bag addons work, some handle gold display differently than others.  So it's one big mess to have to put in support for it.

Of course it's easier for the bag addon author to do it, as all they would have to do is edit their own gold display code for their bag addon.  Though honestly most have their own built in display for that already.

It's because of these reasons that I had no choice but to display it externally as a tooltip.  It just way too much of a hassle to do it any other way.  I do hope you understand and that I've explained so you have a better idea of what is involved.  Sadly though I will have to pass on trying to implement this for the time being.  Though please feel free to always suggest a feature or update you would like.  I try to get back to everyone as quickly as I can.  💚
