### ISSUE TITLE
Request: allow for a whitelist behavior to just track X items

### ISSUE THREAD

**Issue by jsromero98** [Xruptor/BagSync#252]
i love this Addon but i would like it to have the opposite behavior when tracking items, just showing the ones I choose to, for example: i only want to track Marks of honor and Trial of Style tokens, not all my 20 characters armors, weapons, foods and so on, just a short list of items.

**Comment by Xruptor** [comment]
So wait you only want to track a few items?  *scratches head*  On one character or just multiple characters?  Or just the currently logged in character?  Can you give me some examples as this is the first time someone has asked to only track a few items.  😃 I mean I have a general idea of what you want but that would have you inputting itemid numbers for all the stuff you would want to track.

**Comment by jsromero98** [comment]
Yep, its like a kinda lighter version of the database. Track the whitelisted array of itemIDs on all the characters of the acount ( the same span as by default on Bagsync ) and show it as now Bagsync displays it, on the tooltips. not even a separate window. could be useful to whitelist the tracking of coins also but that would be obtional (to be honest i already use SavedInstances to track just a few coins on my characters).

I havent really looked at your code, but if my short coding experience is right, it should be a kinda lighter database.

It would be very verbose on the usability (kinda like, dont track anything until the user specifies in setting which ItemIDs to track in a textbox), but maybe im not alone in only wanting to track some items, and not all.

Other example I would give is like, dont log on another character just to see how much [Concentrated Primal Focus] or [Primal chaos] i have without tracking everything else, just see the tooltip on the charachter i'm logged in (as usual with bagsync).

it was funny to loot a ring on the great vault and see that 4 of my other characters also have it, and 1 of them had 3 copies, but not really as useful as tracking other categories of items and maybe it helps to ease the processing of the dataset.

PD: I love your addon and I use it a lot, just asking for a cherry on top of a great dessert

**Comment by Xruptor** [comment]
Hmm if I'm reading this right, then it would be just much more simplified to have BagSync continue it's scanning procedures and storing all the relative information.  Then only displaying whitelisted items in the tooltips when matching with a user defined itemid list (whitelist).  That way if any itemid's are added then the relative data is already there for charactersand will instantly populate the tooltip, instead of the next time you login to that character.

1) BagSync scans everything as normal, Character A has 50 bags of itemid 1234567 in their bag.
2) User logins to Character B.
3) User cannot see data for Character A with itemid 1234567 as they don't have it whitelisted.
4) User inputs 1234567 into the whitelist while on Character A
5) User can now see 1234567 on Character B since it was already scanned previously.

P.S: I'm glad you enjoy the addon.  😄

**Comment by Xruptor** [comment]
I have implemented this and it will be available in the next major version update push.
