### ISSUE TITLE
Request: Exclude Trader's Tender

### ISSUE THREAD

**Issue by temporicide4** [Xruptor/BagSync#254]
With the addition of an account-wide currency in Trader's Tender, having the tooltip display the amount of Trader's Tender for each character is extremely misleading (because that amount is shared among all characters). There doesn't appear to be a way to add currencies to the blacklist currently, so there's no way to hide that info from the Trader's Tender tooltip.

I would like to request either a currency blacklist feature with Trader's Tender blacklisted by default, or just hard-code an exclusion for Trader's Tender.

**Comment by Xruptor** [comment]
I'll need to look in to this.  Part of the issue is that Currencies use a CurrencyID over and ItemID.  Both of which can share the same number.  So if CurrencyID 2330 is Tenders it can also be ItemID 2330 which is something else.  So blocking on just a number causes complications.  I also try to avoid hardcoding as I've had people file tickets telling me they didn't like that and wanted to see the item I blacklisted by hardcoding.  Either way it's worth investigating and I need to see how I can tackle this.

**Comment by Xruptor** [comment]
After reviewing this, I think in this case it would be best just to hardcode a perm ignore for this currency.  It serves no purpose to show it more than once per character basis.  If someone has an issue with it, then I'll explain it.
