### ISSUE TITLE
Enchancement request: configurable font for BagSync tooltip information

### ISSUE THREAD

**Issue by johndp977** [Xruptor/BagSync#267]
Thank you for writing and maintaining this addon! I've started to use it and since you seem extremely active and responsive to requests and feedback I thought I'd pop in and see if you're open to a few quality of life suggestions.

Love the flexibility to display info in an external tooltip, and I was hoping it would be possible to provide an option to choose the font so I can make it smaller (or whatever I want). I have a lot of alts, and for my uses I display all bnet characters, so the smaller font makes a noticeable difference as the list grows. I think it could be as simple as just a dropdown of some font strings, eg GameFontNormal (probably the default), GameFontNormalSmall, GameFontNormalLarge, etc.

I have some very elementary knowledge of addons, and I was playing around and found that I could tweak the font by hard-coding a line in Tooltip:TallyUnits as follows (after line 627):

objTooltip.qTip:SetFont(GameFontNormalSmall)

However I have no idea if this is the correct or optimal place for it. Also, I do *not* know how easy or feasible it is to allow this flexibility for users that keep the tooltip info embedded in the default tooltip. But my use-case is always with a separate tooltip, so just thought I'd throw it out there as a suggestion. Thanks again for your time and efforts!

**Comment by Xruptor** [comment]
Heya!  I'm glad you enjoy the addon.  Hmm... I don't see why not.  Let me see if I can implement it while I'm working on all these major enhancements for BagSync. I'm constantly streamlining it and trying to improve efficiency while adding new stuff.

**Comment by Xruptor** [comment]
Just to make sure you only want this for the external tooltip right?  I suppose if I did implement this, it probably also affect the built in one as well just to be on the same page with those whom don't like the external tooltip.

**Comment by johndp977** [comment]
> Just to make sure you only want this for the external tooltip right? I suppose if I did implement this, it probably also affect the built in one as well just to be on the same page with those whom don't like the external tooltip.

Yep, my use case is only the external tooltip, thanks!

Agree that ideally it could be applied to any embedded portion as well. I know I've seen tooltips that have varying font sizes and such, I just have no idea how much work it is. Perhaps not as simple as just assigning a font string, but I suppose one could hope it's still easy to apply it to just a portion of the content.

Anyways, thanks again! Might see about sending a few more ideas your way ;)

**Comment by Xruptor** [comment]
So during my rework, I've finally gotten around to finalizing odds and ends and I'm now taking the opportunity to look at tickets.  I did some research into this and have tried to sit there and think of how to properly implement this.  In my research I found that due to restrictions based on the main GameTooltip, it's extremely unreliable to set the Font or FontSize in the standard GameTooltip.  It requires me to scan the tooltip find each line that was modified by BagSync, then grab the line and set the font manually.  Scanning tooltips cause performance drops and I have avoided doing that pretty much everywhere in my addon.  On top of that it would cause erratic behavior for other addons or tooltips that extend past the previously drawn tooltip.  Example, if I modify line 17 to be size 14.  Then the next tooltip that uses that line will be size 14 regardless if it's BagSync or not.

This pretty much leaves only setting the font and size for the External tooltip.  I could add that feature to the external tooltip but I suspect that someone, somewhere will complain that it should be available for the standard GameTooltip.  So I'm at an impasse right now if I should implement this or not.

**Comment by Xruptor** [comment]
I gave this some more thought and I think I'm going to pass on implementing this for the time being.  It's a good idea, I just don't see a feasible way to implement it with the current restrictions on the standard GameTooltip.  Putting it for just the External Tooltip would be unfair for those using the standard GameTooltip method.

**Comment by johndp977** [comment]
No worries, this is your baby and completely your decision.

There does always seem to be a balance between simplicity and flexibility in software. I would say that philosophically, I'm not sure it always makes sense to remove (or omit) a feature completely just because not all users can take advantage of it. The addon already has a few options that are labelled "not recommended" or "may cause lag". But, I can totally understand not wanting to deal with even the potential prospect of confusion or pressure from people using something that you support and offer for free on your own time ;) It's the single reason I've never released an addon of my own...

At the end of the day, this is a very minor thing, and if it becomes too much of a nuisance I can always drop in my own hack each time. Thank you for considering!

**Comment by Xruptor** [comment]
I changed my mind after looking at some other modules I was working on.  I went and added the SharedMedia library and have provided options to change the font, size, outline and monochrome of the font in the External Tooltip.  It will be available in the rework push.
