### ISSUE TITLE
`[*XR]` label in front of same-faction guild on connected realm (in tooltip count)

### ISSUE THREAD

**Issue by tflo** [Xruptor/BagSync#277]
Copied from [here](https://github.com/Xruptor/BagSync/issues/271#issuecomment-1476810971):

Despite having unchecked the "Display [XR] and [BNet] realm identifiers.", I have a `[*XR]` label in front of my connected-realm guild, if I'm logged in to the faction of the guild. Both guilds are connected-realm, but for the guild of the currently opposing faction, the label is not displayed.

If I activate the "Display [XR] and [BNet] realm identifiers.", then I have a `[*XR][XR]` label for the same-faction guild and an `[XR]` label for the opposing-faction guild. 

---

> show me a picture of what you mean for the several occasions you mentioned above

[Explanation of the screenshots in the next section.]

With "Display [XR] and [BNet] realm identifiers." **dis**abled:

<img width="413" alt="WoWScrnShot_032023_205103" src="https://user-images.githubusercontent.com/1410282/226452716-eeca3c68-4c17-48dd-bee4-41ed02c18a2f.png">

With "Display [XR] and [BNet] realm identifiers." **en**abled:

<img width="429" alt="WoWScrnShot_032023_205358" src="https://user-images.githubusercontent.com/1410282/226452785-8640552b-247f-485f-b0f8-1017079a9ed6.png">

---

> Break it down for me by faction, realm, and connected realm

My main activity is on a [Connected Realm](https://us.battle.net/support/en/article/14296). **All** my chars are on one "sub-realm" of the connected realm (Azjol-Nerub), **both** guilds (i.e Horde and Alliance) are on the other sub-realm (Quel'Thalas).

_The screenshots were made while on an Alliance char._ The Alliance guild is "Dark Souls of Azeroth", the Horde guild is "Tremors".

The same-faction guild (= same faction as the logged-in char), that is "Dark Souls of Azeroth" on the screenshots, shows the `[*XR]` label, while the opposing-faction guild ("Tremors") does not.

When I'm on a Horde char, it is analogous: The same-faction guild, which is "Tremors" then, shows the `[*XR]` label, while the opposing-faction guild ("Dark Souls of Azeroth") does not.

**Comment by Xruptor** [comment]
Okay I think I know what it is.  I'm going to make it so all the TAG options are honored when displaying stuff other then forcing it.  I think that's the issue going on here.  This includes the option to show tags at all.  When that is disabled then I will force a small indicator for just XR guilds.

In addition.  I don't like the cross realm guild being too similar to the other XR realms.  I'm going to change it to a plus sign instead since asterisk is an option in the BagSync tag config.  It should be [+] or [+XR].

Please try this version, I even added the colored LEVEL for the battle pets in the details window.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11022938/BagSync.zip)

Let me know if works properly for you.

**Comment by Xruptor** [comment]
Oh and please show me a picture so I know the changes are looking nice :)

**Comment by Xruptor** [comment]
Oh BTW the cross realm marker for a guild should ONLY be displaying if you have both of these options **disabled**.

- Display Battle.Net Account characters. [BNet] (Not Recommended)
- Display Cross-Realms / [Connected Realms] characters. [XR]

If both of those options are disabled then technically the guild would never show up for a user.  In order to process the guild even if those options are disabled, I check for both to be off.  If they are both off and a players guild matches the DB guild but don't share the SAME server, then it displays the guild with the special marker [+].  To let folks know the guild is being forcefully shown because the **currently logged in character** is part of that guild.  Otherwise if any of the options above are enabled the guild would show up normally.  Either with the BNET tag for the first option or the XR tag on the second option.

It has nothing to do with the "Display [XR] and [BNet] realm identifiers." option btw.

**Comment by tflo** [comment]
Basically it's the same, just the double tag with "Display [XR] and [BNet] realm identifiers." is gone:

Without "Display [XR] and [BNet] realm identifiers.":

<img width="262" alt="WoWScrnShot_032023_215243" src="https://user-images.githubusercontent.com/1410282/226465534-2d32684f-53b7-49fe-a538-10202a1e5d08.png">



With "Display [XR] and [BNet] realm identifiers.":

<img width="283" alt="WoWScrnShot_032023_215256" src="https://user-images.githubusercontent.com/1410282/226465371-04e4c01d-2e06-4766-a44f-e52466100f63.png">

This is, like the previous screenshots, while logged into an Alliance toon.

But, I think, you are not getting my point:

- With all tag options disabled, I expected to see no tags at all
- Both guilds are on the other connected sub-realm (Quel'Thalas) than all the chars (Azjol-Nerub). So, – in my understanding – both guild banks should have exactly the same tag – if tags are enabled.

In case you don't believe me, here with the literal sub-realm names:

<img width="344" alt="WoWScrnShot_032023_215925" src="https://user-images.githubusercontent.com/1410282/226466672-3b74493a-b0d9-4867-9bd7-39aa71ff53d8.png">

---

Oh and please show me a picture so I know the changes are looking nice :)

Here the color-coded pet rarity:

<img width="917" alt="WoWScrnShot_032023_215451" src="https://user-images.githubusercontent.com/1410282/226467855-ebba1347-646d-42ff-adad-ccd2fbd5e4e2.png">

**Comment by tflo** [comment]
We have cross-posted now. I will post an image of the settings in a few minutes.

**Comment by Xruptor** [comment]
Scroll up I posted before you.

**Comment by tflo** [comment]
> Scroll up I posted before you.

Yeah, that's what i meant with cross-posted ;)

**Comment by Xruptor** [comment]
Also are you showing these results from the advanced search screen?  Because of you are then those options will always force the tag identifiers.  That's by design.  You should use the regular search window.

**Comment by tflo** [comment]
These are tooltips from the regular list (not advanced). Images in  a few seconds…

**Comment by tflo** [comment]
<img width="1077" alt="WoWScrnShot_032023_222527" src="https://user-images.githubusercontent.com/1410282/226470246-fd4ca2b8-bbc6-470d-bb6d-4b0af3418f16.png">

<img width="1046" alt="WoWScrnShot_032023_222538" src="https://user-images.githubusercontent.com/1410282/226470273-db487a29-2927-4cc9-b027-bb0b42ce0f42.png">

<img width="1069" alt="WoWScrnShot_032023_222551" src="https://user-images.githubusercontent.com/1410282/226470310-b8e4efce-d94a-4552-a449-57fdc1adde01.png">

<img width="1073" alt="WoWScrnShot_032023_222601" src="https://user-images.githubusercontent.com/1410282/226470324-533642fa-bf1b-484b-8f11-f524fbb59b34.png">

**Comment by Xruptor** [comment]
![image](https://user-images.githubusercontent.com/202515/226471231-914423a3-330b-43f3-9182-898cfd81de44.png)
It should not be displaying the [+] with the option enabled.  That's a bug.  It should ONLY show that if both Account-Wide options are disabled.  In that scenario it should have just shown Dark Souls but without the identifier.

![image](https://user-images.githubusercontent.com/202515/226471487-5098f359-c6d6-4d06-a941-26fb9e98c671.png)

This one is working properly.  With both options disabled it's showing you the guild with the [+] tag because you are logged into a toon that is in that guild even if it's on a connected realm.

![image](https://user-images.githubusercontent.com/202515/226471616-2940654f-6636-49e3-8665-0e66d32c74af.png)

Again it should not be showing the [+] tag.  I'm a bit baffled as I do a check to make sure both options are disabled.  Somehow it's being turned on.  It should only be showing the [XR] tag for both.

![image](https://user-images.githubusercontent.com/202515/226471776-25f8307a-1ef4-457a-b5f3-bd075433bff6.png)
This one is working correctly technically.  It's not showing Tremors because you don't have cross realms XR enabled.  It's only showing you Dark Souls because your current character that is logged in is part of that guild.


Let me take a quick look at the logic.  It should not be displaying [+] if both options are disabled.  That's a bug.

**Comment by tflo** [comment]
> ![image](https://user-images.githubusercontent.com/202515/226471231-914423a3-330b-43f3-9182-898cfd81de44.png) It should not be displaying the [+] with the option enabled. That's a bug. It should ONLY show that if both Account-Wide options are disabled. In that scenario it should have just shown Dark Souls but without the identifier.

Yep, that's what I meant: With all tag options disabled i expect to not see any tags. (The exception that you display the `+` for the membership guild if XR is disabled makes sense though.)

**Comment by Xruptor** [comment]
I'm going to need your BagSync.lua file.  Something is going on and the logic is still assigning the XRGuild tag when it shouldn't,  That should only display if both options are disabled (for obvious reasons, since the current character is part of a guild that is on an XR realm, so it needs to be shown regardless of settings.)  Perhaps I can see where it's turning it on.

**Comment by tflo** [comment]
[BagSync.lua.zip](https://github.com/Xruptor/BagSync/files/11023323/BagSync.lua.zip)

**Comment by tflo** [comment]
Btw, concerning the "Display Cross-Realms / [Connected Realms] characters" setting:

I would not treat 1) true cross-realms the same way as 2) cross-realms on the same connected realm. The latter is irrelevant _for the player_, since linked realms are behaving as if they were the same realm. In the case of true cross-realms though (not connected, independent realms), it _is_ important, because you cannot send items/gold there (except account-bound stuff).

**Comment by Xruptor** [comment]
Both cross and connected realms are treated exactly the same in Blizzard code.  It's actually returned as a cross realm.  Also I've had people in the past ask me to show identifiers for it if they enable it.  That's why it's done that way even if it's a connected realm.

**Comment by tflo** [comment]
> Also I've had people in the past ask me to show identifiers for it if they enable it

The identifiers are fine, if someone wants to see them.

I meant the merging of the count display itself into one option (but maybe I am misreading the setting):

If I do not want to see the item counts of toons on another (not connected) realm, than there is a good reason for it: I do not have access to those items from the other realm, they are rather clutter in the tooltip.

But if I disable the "Display Cross-Realms / [Connected Realms] characters" option, then I will also no longer see the item counts of the chars on the linked realm (on the connected server), or the other-faction guild bank (on the linked realm) in my case.

**Comment by tflo** [comment]
But sorry, I'm going OT once again ;)

**Comment by Xruptor** [comment]
I found the issue, it was being overwritten on a local player guild check.  That is why it kept showing.

Also no worries.  Just treat Connected Realms as Cross Realms for all intent and purposes with BagSync.  In the Blizzard code that's how they are handled BTW.  So I use the same code they do.  https://wowpedia.fandom.com/wiki/API_GetAutoCompleteRealms

What I can do however is just reword all instances of Cross Realms to Connected Realms to make it easier to understand.

**Comment by tflo** [comment]
Ah, damn, I was indeed misreading it. Just logged into a different-realm (Draenor, not connected) char to verify, and, indeed, items from my main realm are not shown there, no matter the checkmark on that option. (I could not see it the other way round before, because my char there is an inactive cross-realm pet trader who currently has _nothing_ in her bags ;)

The slash in the settings text was misleading me, I read it as 'cross realm' AND 'connected realm'.

I found out now that the real cross-realm setting is the "Display Battle.Net Account characters" one. (I was always thinking that this would refer to chars on other accounts on the same BNet account, and I was wondering how you would do that…)

**Comment by Xruptor** [comment]
Yes that is how that works.  I'll just rename Cross Realms to Connected Realms to make it easier to understand.

**Comment by Xruptor** [comment]
I'll also change the XR tag to CR instead

**Comment by tflo** [comment]
Thank you, tags are displayed as expected now with 19.2.
