### ISSUE TITLE
BagSync and Elvui bag item border

### ISSUE THREAD

**Issue by phoenix0217** [Xruptor/BagSync#287]
https://prnt.sc/WFKZBLrlN3IG
Sometimes my bag will not show border with BagSync

**Comment by phoenix0217** [comment]
[](https://prnt.sc/WFKZBLrlN3IG)

**Comment by Xruptor** [comment]
I don't think I understand the issue?  BagSync doesn't touch anything in regards to the UI Bags.  The only thing it does is add additional content to the game tooltip.  It does this by using Blizzards own new tooltip processing functions they made for Dragonflight, that's about it.  BagSync also does a lot of data collecting in the background but the only real UI element that is altered is the tooltips.  In terms of the bags, they are scanned using Blizzards Bag functions and API, but again nothing that would affect any UI elements.

Are you absolutely certain it's just BagSync?  Does this issue happen at all in other scenarios, like with BagSync disabled?  You said "sometimes" so it sounds like it's not an issue you can always reproduce.  Perhaps it's an actual issue with ElvUI and not BagSync?  See if you can pinpoint it exactly.  If the issue is replicated even with BagSync off then it could be an ElvUI issue.

**Comment by phoenix0217** [comment]
ah u're right, sorry about that.
it still happen after i disable BagSync.

**Comment by Xruptor** [comment]
Not a problem, hope you figure it out!
