### ISSUE TITLE
Void Storage NOT Tracked when using Bagnon Void Storage

### ISSUE THREAD

**Issue by Jayshua83** [Xruptor/BagSync#29]
As title says... Void Storage NOT Tracked when using Bagnon Void Storage.

Known issue?

**Comment by Xruptor** [comment]
This is the first I hear of this issue.  In general Bagnon uses the very same Blizzard API when it grabs the information about Void Storage from the servers.  The only way I can think that the Void Storage will not be tracked by BagSync is if Bagnon hijacked the functions required for BagSync to properly work.  However, that's highly unlikely because Tuller is very good at how he programs.  I'm sure he did what I did and monitored event calls for Void Storage.  I don't have an active account right now to test this out.  Hopefully someone will take a look at it and provide a fix via GitHub.

**Comment by Jaliborc** [comment]
Well, I'm not Tuller, but I will take the complement nonetheless.
I did double-checked and Bagnon Void Storage is not fiddling with any function, as it should. As an additional point, BagBrother, which works independently, is able to track the void storage.

**Comment by Xruptor** [comment]
Hey jailborc.  I've just finished up a huge revamp of BagSync and migrated it to Ace3.  I'm going to be monitoring this bug and see if it still happens.  Hopefully it doesn't still occur.  I will be released BagSync 10.0 soon.

**Comment by Xruptor** [comment]
Okay apparently it has to do with the Void tooltips in Bagnon.  They aren't working even with Bagsync Disabled.  If I hover over an item in Bagnon Void Storage no tooltip ever appears.  Now BagSync also has an issue, it appears that when using SetVoidItem, SetVoidDepositItem or SetVoidWithdrawalItem the GetItem() for the tooltip returns nil.  So I will see what I can do about that.  You should take a look at the tooltips in Bagnon Void Storage.  I had BagSync disabled and it still didn't show tooltips for me with the Void Storage items.

**Comment by Xruptor** [comment]
Alrighty, I've gone ahead and made some hooks to the appropriate functions.  If by some chance GetItem() returns nil, then the other functions will catch it and still display the BagSync tooltip information.

It should work once the tooltips on Bagnon VoidStorage gets fixed.

Here are the changes: https://github.com/Xruptor/BagSync/commit/286379904600ff4aa89b560ff2e548d339128cef

**Comment by Xruptor** [comment]
Also apparently this bug has already been documented on Bagnon :)

https://github.com/tullamods/Bagnon/issues/485

**Comment by Jaliborc** [comment]
@Xruptor, how is BagSync pulling those tooltips then? Did Blizzard change the functions for voidstorage, instead of using SetVoidItem, SetVoidDepositItem or SetVoidWithdrawalItem?

**Comment by Xruptor** [comment]
BagSync makes a general safe hook to OnTooltipSetItem script for the GameTooltip and ItemRefTooltip.  This script is usually fired by any function that sets an item link on the Tooltip itself.  So I pretty much use it as a capture all to add the additional bagsync lines.  The problem with only relying on OnTooltipSetItem is that sometimes the GetItem() call from it returns nil for the item that was set by the parent function. (This is a known bug on Blizzards end).  This normally happens with things like SetHyperLink and a few others.  In order to compensate for this, I do secure hook to the original function that initially sets the item link on the tooltip.  Then I grab the link from there using the appropriate GetItemInfo() method.  This creates a fallback as OnTooltipSetItem is still fired immediately afterwards anyways.  So what I do is save the hyperlink and let OnTooltipSetItem take care of it.  There is a few times that OnTooltipSetItem isn't fired though on particular frames.  In those instances I just do the tooltip modification from the original set function from the secure hook.  I have checks for this though just in case something didn't get added or fired.

With Bagnon I was able to determine that the tooltips from the Void Storage module was returning nil on GetItem() from within OnTooltipSetItem.  So what I did instead was secure hook the original set item  functions to grab the link from there.  I tested this myself with the default UI and it works flawlessly.

However it still doesn't work with Bagnon because apparently Bagnon isn't displaying tooltips properly for Void Storage.  Jaliborc, I want to point out again though that the tooltips for the Void Storage on Bagnon weren't working even after I disabled all my addons (this includes BagSync).  So something is wrong on that end.  Apparently there is an active ticket on it.  So it can't be BagSync causing this problem.  I don't replace any functions on the tooltips.  I only do safe secure hooks and hook scripts.  Then add additional lines to the existing tooltip information.

I will look into it a bit more but I'm not entirely familiar with the Bagnon code to determine why the tooltips aren't displaying properly on Void Storage.

**Comment by Xruptor** [comment]
Okay just realized there are two tickets about the Void Storage not working properly on Bagnon.  One of them seems to be the original poster of this ticket.  He was having a similar issue with the Void Storage as the other ticket.

https://github.com/tullamods/Bagnon/issues/425

and

https://github.com/tullamods/Bagnon/issues/485

**Comment by tflo** [comment]
Just as a note: It seems this problem has come back with Bagnon 10.0.14 / BagSync 18.3 / Retail 10.0.2.

Void Storage is sometimes tracked, sometimes not. Sometimes even a previously cached Void Storage disappears after having opened the Void Storage.

Since yesterday I have unloaded Bagnon/BagBrother and haven't seen the issue – so far.

**Comment by Xruptor** [comment]
> Just as a note: It seems this problem has come back with Bagnon 10.0.14 / BagSync 18.3 / Retail 10.0.2.
> 
> Void Storage is sometimes tracked, sometimes not. Sometimes even a previously cached Void Storage disappears after having opened the Void Storage.
> 
> Since yesterday I have unloaded Bagnon/BagBrother (on all 20 chars) and haven't seen the issue – so far.

This issue was related to how Bagnon was handling the tooltips.  If you want to see if the voidbank is scanned on BagSync.  Do the following.

- type **/bgs debug**
- Enable the debugging
- make sure **DEBUG**, **INFO** is checked.
- Open the Void Bank, the Scanner should "**SaveVoidBank**" with a **true**.

As this issue was a Bagnon problem and not a BagSync issue, you should really mention it as a ticket over there.  It was an issue at the time and @Jaliborc fixed it.  Perhaps it resurfaced again?  He should really know about it on his end.  In the meantime I'll load Bagnon myself and see where the issue lies if I can help.

Please checkout https://github.com/Jaliborc/Bagnon/issues/425 and https://github.com/Jaliborc/Bagnon/issues/485

In terms of the tooltip display, I'm using Blizzards new method they introduced with DragonFlight.
https://wowpedia.fandom.com/wiki/Patch_10.0.2/API_changes#Tooltip_Changes

**Comment by Xruptor** [comment]
Whoops forgot to @tflo mention you in that last comment lol. XD

**Comment by tflo** [comment]
> Whoops forgot to @tflo mention you in that last comment lol. XD

No worries, got the mail notification nonetheless.

> Perhaps it resurfaced again? He should really know about it on his end.

Seems so, yes. Not going to post it over there, as I have uninstalled Bagnon for good. Was only testing it for a couple of days anyway, but it has too many issues and does scary things (I have already posted two of them to Jaliborc in the last days; not going to link them here as they are not related).

> If you want to see if the voidbank is scanned on BagSync. Do the following. […] /bgs debug

OK, thanks for the info. Will try it next time when I have issues.

My method for testing for the Void Storage cache was simply: 
1. Advanced search for the Void Storage of the current char (immediately after the visit of the Void Storage).
2. If it returns nothing, hit Refresh a couple of times.
3. If it still doesn't return anything, I was assuming that it was not cached.

– Tom

**Comment by Xruptor** [comment]
> > Whoops forgot to @tflo mention you in that last comment lol. XD
> 
> No worries, got the mail notification nonetheless.
> 
> > Perhaps it resurfaced again? He should really know about it on his end.
> 
> Seems so, yes. Not going to post it over there, as I have uninstalled Bagnon for good. Was only testing it for a couple of days anyway, but it has too many issues and does scary things (I have already posted two of them to Jaliborc in the last days; not going to link them here as they are not related).
> 
> > If you want to see if the voidbank is scanned on BagSync. Do the following. […] /bgs debug
> 
> OK, thanks for the info. Will try it next time when I have issues.
> 
> My method for testing for the Void Storage cache was simply:
> 
> 1. Advanced search for the Void Storage of the current char (immediately after the visit of the Void Storage).
> 2. If it returns nothing, hit Refresh a couple of times.
> 3. If it still doesn't return anything, I was assuming that it was not cached.
> 
> – Tom

@tflo Oh sorry to hear that.  He works hard on the addon and I know it has a lot of issues because it deals with a fundamental element essential to gameplay, which is the bags and storage.  Since it's a replacement to the Blizzard UI, it's bound to have issues and honestly Blizzard has pressed really hard into the **FORBIDDEN** and **TAINT** departments when it comes to restricting code lately.  So there is a lot of bugs and work to be done with it.

In terms of dumping Bagnon, you aren't the only one. I've been getting messages from folks whom have abandoned Bagnon and used the new Blizzard Combined bag with my addon.  If I recall one of them mentioned Blizzmove I think it was?  https://www.curseforge.com/wow/addons/blizzmove to move around the bags.  Which is pretty much all they needed to make it feel exactly what they wanted.

There are a few other alternatives I think if you are still looking for another bag addon.  Otherwise don't forget Blizzard now has a combined bag option.  Just right click the Bag icon when you open the bags and select "combined bags".
https://www.method.gg/dragonflight-introduces-a-reagent-bag-slot-increased-stack-sizes-and-combined-bags-option

https://www.curseforge.com/wow/addons/ark-inventory
https://www.curseforge.com/wow/addons/litebag
https://www.curseforge.com/wow/addons/onebag3
https://www.curseforge.com/wow/addons/baggins
https://www.curseforge.com/wow/addons/baud-bag

**Comment by tflo** [comment]
Currently I'm back to AdiBags. Was using AdiBags, alternating with ArkInventory, during the last 3 or 4 years. 

Last week I had the spontaneous idea to test the simpler addons (i.e. bag display without an additional abstraction layer). The most satisfying one I found was LiteBag by xodiv. 

But after a week I got tired of manually arranging the contents of my bags (or disarranging them by clicking Blizz's Sort button), so back to the old ;)

In terms of inventory tracking, I have more than enough running: Armory, Stash, Altoholic, TSM, and now test-wise BagSync :)

**Comment by tflo** [comment]
As I said "_test-wise_ BagSync": So far, I like it a lot, and it will probably be a stayer. It has two supposedly tiny features that are really useful:

- The _colored_ current-char indicator in the tooltip counts (emphasis on 'colored', since ArkInventory has this too, but non-colored)
- The ability to sort the tooltip counts by quantity; incredibly helpful, and astonishing that none of the other inventory addons offer this (at least to my knowledge)

**Comment by Xruptor** [comment]
> As I said "_test-wise_ BagSync": So far, I like it a lot, and it will probably be a stayer. It has two supposedly tiny features that are really useful:
> 
> * The _colored_ current-char indicator in the tooltip counts (emphasis on 'colored', since ArkInventory has this too, but non-colored)
> * The ability to sort the tooltip counts by quantity; incredibly helpful, and astonishing that none of the other inventory addons offer this (at least to my knowledge)

@tflo Thanks I'm glad you are enjoying it.  I try to take feedback and feature requests into consideration and review the possibility of adding them.  The total sorting was one of them.  If you come across any bugs of have a feature request, please feel free to file a new ticket.  :)  We should try to stop posting here as everyone in here will get a notification LOL.
