### ISSUE TITLE
Travers tender tooltip is missing

### ISSUE THREAD

**Issue by martinboy1974** [Xruptor/BagSync#299]
When mousing over traders tender in the curency window, tooltip doesnt show how many I have.

**Comment by Xruptor** [comment]
Hello!  Thank you so much for filing a ticket.  :)

That isn't a bug actually.  Trader's tenders are shared with all your characters on the entire server.  Meaning that if you current character has 33, then all your other characters will have 33.  Check it out :)  Login to other characters and you'll see what I mean.  It was pointless to display a tooltip with every character showing 33, so it was disabled.  Especially since it was tallying up the same results and showing more tenders then the account actually has.
