### ISSUE TITLE
LUA error on PTR

### ISSUE THREAD

**Issue by sausje** [Xruptor/BagSync#308]
On PTR I'm getting the following error:

> 1x BagSync/modules/config.lua:1273: The parent category 'BagSync' was not found
> [string "=[C]"]: ?
> [string "@Atlas/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:2006: in function `?'
> [string "@BagSync/modules/config.lua"]:1273: in main chunk
> 
> Locals:
> (*temporary) = "The parent category 'BagSync' was not found"

and this one too

> 1x BagSync/modules/config.lua:1 (null)

and

> 1x Interface_Wrath\FrameXML\Bindings.xml:1 BagSync/modules/config.lua:1 (null)

Idk if it has to do with me copying the config from live wrath?

**Comment by Xruptor** [comment]
Are you going from Live Wrath to PTR Wrath?

**Comment by Xruptor** [comment]
I should have time tomorrow to look at this.  I've been a bit busy as of late lol.  Hopefully I can debug it on the PTR as I don't have an active subscription anymore.

**Comment by sausje** [comment]
If you need some help debugging it just let me know!

**Comment by Xruptor** [comment]
Hey @tflo I don't suppose you can verify this?  >.> not sure if I can mention other people in a ticket LOL.

> If you need some help debugging it just let me know!

That would be of tremendous help 😃.  I have a suspicion that it may be Ace Libraries that need to be updated.  Either way it's worth investigating into.  I'll let you know tomorrow :)  (or tonight if I get some time)

**Comment by tflo** [comment]
> not sure if I can mention other people in a ticket LOL.

I didn’t know either, but it seems we can. I got a mail notification because of the mention.

I have a semi-abandoned char on Wrath (from the mount promo), but no Wrath PTR though. I’ll try to create a Wrath PTR account a bit later. (Today or at latest tomorrow.)

**Comment by tflo** [comment]
Well, I did it already, installation was painless.

I get this error _without_ having copied any config (BagSync.lua) from Wrath Live, i.e. at a fresh start:

```
1x BagSync/modules/config.lua:1273: The parent category 'BagSync' was not found
[string "=[C]"]: ?
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:2006: in function `?'
[string "@BagSync/modules/config.lua"]:1273: in main chunk

Locals:
(*temporary) = "The parent category 'BagSync' was not found"
```

**Comment by Xruptor** [comment]
Okay I did a little research into this.  Apparently it seems they have completely redone the settings menu... yet... AGAIN.  If you notice on the WOTLK Classic server, you can't access the Addons Settings panel anymore.  You used to be able to have a tab with "Addons" in the Interface options menu to see addon settings under there.  Currently that isn't even available in the WOTLK PTR.  BagSync is can force it to open but it isn't fully implemented anymore on the actual server.  Since you aren't supposed to access it normally there.  I suspect this is the cause of all the problems on the PTR.  It's generating an error for a panel that doesn't even exist.

If this is the case and they go through with this, it will royally upset a lot of addon authors as they would have to rewrite the settings panels yet again.

**Comment by tflo** [comment]
I can open the 'AddOns' tab with `/bgs config`, but BagSync’s sub-entries are missing:

![WoWScrnShot_051723_102409](https://github.com/Xruptor/BagSync/assets/1410282/e57f4d94-4dc5-4c99-b724-f485c73af6ab)

And btw, it seems Blizz themselves don’t know how to handle their Settings panel, as I get this (apparently macOS-specific) error right at login:

<details>
<summary>Details</summary>

```text
Message: Interface/SharedXML/Settings/Blizzard_Setting.lua:9: 'name' for variable 'MacDisableOsShortcuts' requires string type.
Time: Wed May 17 10:12:25 2023
Count: 1
Stack: Interface/SharedXML/Settings/Blizzard_Setting.lua:9: 'name' for variable 'MacDisableOsShortcuts' requires string type.
[string "=[C]"]: in function `error'
[string "@Interface/SharedXML/Settings/Blizzard_Setting.lua"]:9: in function <Interface/SharedXML/Settings/Blizzard_Setting.lua:7>
[string "@Interface/SharedXML/Settings/Blizzard_Setting.lua"]:175: in function `Init'
[string "@Interface/SharedXML/Mixin.lua"]:50: in function `CreateAndInitFromMixin'
[string "@Interface/SharedXML/Settings/Blizzard_Settings.lua"]:190: in function `RegisterCVarSetting'
[string "@Interface/SharedXML/Settings/Blizzard_Settings.lua"]:490: in function `SetupCVarCheckBox'
[string "@Interface/SharedXML/SettingDefinitions/Mac.lua"]:5: in function <Interface/SharedXML/SettingDefinitions/Mac.lua:1>
[string "=[C]"]: ?
[string "@Interface/SharedXML/Settings/Blizzard_SettingsRegistrar.lua"]:28: in function `AddRegistrant'
[string "@Interface/GlueXML/SettingDefinitions/Mac.lua"]:5: in main chunk

Locals: (*temporary) = "'name' for variable 'MacDisableOsShortcuts' requires string type."
```

</details>

**Comment by Xruptor** [comment]
Yes you can but you'll notice the code on the WOTLK PTR is super buggy.  The addon tab is even missing the word "Addons".  In addition you'll notice a few addons on the older interface screen don't show up in the new one.  This is because a lot of stuff is being depreciated.  It's one huge mess and honestly I'm getting super tired of them redoing entire frameworks every freaking expansion.  Then folks wonder why so many addons authors just walk away sometimes.

I'll put together a workaround to try to compensate for the two different settings windows after my errands today.

**Comment by Xruptor** [comment]
Please try this version and let me know.
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11503799/BagSync.zip)

P.S: The addon tab in WOTLK PTR settings is missing the word "Addon" that isn't BagSync causing the issue.  PTR in general can sometimes be super buggy.  That's the whole point of it, to test stuff.

**Comment by sausje** [comment]
> Please try this version and let me know. [BagSync.zip](https://github.com/Xruptor/BagSync/files/11503799/BagSync.zip)
> 
> P.S: The addon tab in WOTLK PTR settings is missing the word "Addon" that isn't BagSync causing the issue. PTR in general can sometimes be super buggy. That's the whole point of it, to test stuff.

Here no more LUA error and it's showing up properly in the new addon settings now.

**Comment by nanjuekaien1** [comment]
[https://github.com/Stanzilla/WoWUIBugs/issues/431#issue-1701020426](url)

**Comment by nanjuekaien1** [comment]
Look here

https://github.com/Stanzilla/WoWUIBugs/issues/431

**Comment by Xruptor** [comment]
> Look here
> 
> [Stanzilla/WoWUIBugs#431](https://github.com/Stanzilla/WoWUIBugs/issues/431)

Yeah I knew it had to do with them depreciating the settings panel from the older UI.  So I compensated for both and did a check for it in that test build above.
