### ISSUE TITLE
Tooltip trigger "useContainterItem"

### ISSUE THREAD

**Issue by Xpatro** [Xruptor/BagSync#311]
Was standing at the Artisan Consortium tried to create an Public order, as the window was opened i right clicked on my rousing orders to create an Awakening Order.

Suddently it blocked the action and had to drag rousing to action bar to be able to combine to an awakening...

Error:
3x [ADDON_ACTION_FORBIDDEN] AddOn 'Ace3' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1402: in function <FrameXML/ContainerFrame.lua:1311>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1454: in function <FrameXML/ContainerFrame.lua:1441>

**Comment by Xpatro** [comment]
Note: Just updated the to latet Bagsync before i logged in and this happened... :(

**Comment by Xruptor** [comment]
This seems to be an error on Blizzards part.  If you notice the error is UNKNOWN().  That means that not even Blizzard could generate the error properly on their end.  I suspect there is a bug with their UI code that fired it.  The first thing it hit was Ace3 which is a popular library that a ridiculous amount of addons use.  No where in that error line was BagSync ever mentioned.  So it could have been any other addon that triggered it that uses Ace3, not just BagSync.  If you notice at the bottom also that container frame stuff is the generic standard Blizzard bags functions.  I think either the issue is on their end with "**UseContainerItem**" or some other addon use triggering it.

Lastly, BagSync doesn't use the "UseContainerItem" at all anywhere in the code.  What I suggest is if the issue happens again.  Disable all addons and try performing the same action.  If no error occurs, then enable all addons except BagSync (leave it disabled) and see if still occurs.  If it does then it isn't BagSync.  Otherwise, enable BagSync and test it again, if the error still occurs then I need to look into it as I'm not sure what would cause it.

**Comment by Xruptor** [comment]
Okay a little research.  This is a known WOW UI bug that pops up every so often.  It happens with Dragonflight and with certain bag addons like Bagnon and what not.  Also sometimes occurs using Blizzards OneBag system.  Folks recommend doing a /reload to fix it.

https://github.com/Stanzilla/WoWUIBugs/issues/310

https://github.com/Jaliborc/Bagnon/issues/1579

**Comment by Xpatro** [comment]
ay well not using any wow bag addons except for your Bagsync.

**Comment by Xruptor** [comment]
> ay well not using any wow bag addons except for your Bagsync.

Hmm.. well it could have been the built in Blizzard UI.  It does trigger as an issue according to UI Bugs.
https://github.com/Stanzilla/WoWUIBugs/issues/310

Do you use ElvUI or any other major addons?  Anything that would reskin, rework or do anything with the bags at all?  The error was with Ace3 so I'm trying to rule out other addons.  It could have been a brief freak accident.  If you can constantly repeat the error then that's a problem.  You'd have to disable addons to see what is causing it.  It's sort of hard to determine with a generic error like UNKNOWN() and in Ace3.

**Comment by Xruptor** [comment]
I haven't heard back in 5 days? I'm assuming it has been resolved?

**Comment by Xruptor** [comment]
Closing this issue.  I haven't heard back in a week now.
