### ISSUE TITLE
Feature Request: Track Merged Realms

### ISSUE THREAD

**Issue by Uggers** [Xruptor/BagSync#32]
I have a set of alts crossed across 2 realms that got merged so essential the same realm.
However I can only view info if i log onto a alt on that half of the realm

Is it possible to have it so can recognise the realm is merged by have -Emerald Dream or -Terenas at the end of the chars name for example

Maybe make it optional so people can turn off that function if they only play on one realm even if its merged

**Comment by Xruptor** [comment]
It is technically possible to implement what you are requesting.  They have added API to make grabbing cross-realm information much easier.  There is the problem though of an active subscription.  I don't plan to resubscribe anytime soon.  Possibly when Legion comes out but right now my focus is elsewhere in terms of MMO's.  If someone were to contribute the code I would be more then pulling to push it to the master build for release.  Check back when Legion comes out and this may be implemented ;)

**Comment by Xruptor** [comment]
v8.6
Added Cross Realm Support and BNet Account Support
-This is a big update as I've added support for both Cross Realms and BNet account.
-Please note that BNet account option will only show character items for the CURRENTLY LOGGED IN BNET ACCOUNT.  It will not show characters from multiple BNET accounts as this is currently not possible with how Blizzard setup saved variables in game accounts.
-Cross Realm / BNet Account support does take the FACTION option into account.  So if you have that enabled it will only display characters of the same faction on both Cross Realm and BNet Account
-It is NOT recommended to turn on BNet account items.  This is a lot of data and it should be only used on really fast computers.  Consider yourself WARNED if you experience lag.
-Cross Realm support is enabled by default.
-You may have to login/logout once or twice for it to fully take effect.  The database has been updated to store character realms to assist in the tooltip process.
-If you use /bgs profiles and want to delete the information of a Cross Realm or BNET Account character.  You need to LOGIN on that server in order to do this.  I will be adding the ability to delete characters from different servers in the future.  Right now it's not a priority.
-Added new localization strings for the new options.  This will have to be updated by folks as they translate it for me.

I've tested this on several characters on different servers.  Some with the same name and others not.  Everything worked as expected.  Please let me know if you get any bugs.
