### ISSUE TITLE
[Feature] Display Warband Currencies with "Warband" icon instead of being associated to a character

### ISSUE THREAD

**Issue by F-Lambda** [Xruptor/BagSync#351]
With the implementation of the Warband Bank as a location, Warband Currencies should also be marked as total for the warband, instead of displaying a character name.

Currently, the only Warband Currency I know of is Trader's Tender.

From
![image](https://github.com/user-attachments/assets/7791d443-7ace-4519-889b-4aafbcdd179e)

to
![image](https://github.com/user-attachments/assets/72027eac-d4aa-41f0-a56e-f7026391f930)

**Comment by Xruptor** [comment]
I'd have to give this some thought.  Not sure if I'd implement this but it's worth consideration.

Aside from Tenders, even if I were to merge the currencies into one location, the currencies are still located on their respected character.  Meaning you still would have to transfer them from a source player to the active player.  It's not really all in one location at the moment.  So putting it all in one location wouldn't make sense because you would be like.  Well I have "100 Pet Charms".  Oh wait no I don't I have to transfer them first.  So that's the primary reason I still would prefer to have them separated.  If all the currencies were instantly shared by all characters then I would definitely have merged them all.  I hope that makes sense.

**Comment by F-Lambda** [comment]
Yeah, this would be specifically for Tenders atm, cause it's the only one that's a Warband Currency and not Warband Transferrable.

**Comment by Xruptor** [comment]
I checked the code and apparently it's still treated as a separate token even if it's a warband currency.  That's really lazy on Blizzards part.  I'll probably have to check for `C_CurrencyInfo.IsAccountWideCurrency` but that applies to all over currencies that are transferable too.  Sometimes I see how they implement things and just *facepalm*.

Thankfully I tackled some of this in the ticket #343

**Comment by Xruptor** [comment]
Apparently the PTR is having issues right now with Warbands.  Tenders don't work on PTR servers.  Soooooo you will need to check for me.

Please note this affects ONLY tenders.  Let me know if this works for you.

[BagSync.zip](https://github.com/user-attachments/files/16614388/BagSync.zip)

**Comment by F-Lambda** [comment]
Hmm, seems to not quite be working properly yet, though it might have to do with currency transfer being disabled by Blizz at the moment. I'll check again later. One feedback, I would also remove the "Account-Wide" text, personally.

![image](https://github.com/user-attachments/assets/a1111cf8-47ac-448d-93e4-05b92827121a)
