### ISSUE TITLE
Cataclysm Classic - no professions window?

### ISSUE THREAD

**Issue by ThaDanus** [Xruptor/BagSync#368]
Hi, just downloaded this addon to keep track of my alts bags and professions, but I can't find the professions window?
![2024-08-20 13_11_54-World of Warcraft](https://github.com/user-attachments/assets/a34b8964-52e1-4f86-b641-b27ba6f089cb)

Don't see anything listed on the addon page about professions not being supported in Cata classic, is this the case perhaps?

**Comment by Xruptor** [comment]
So yes it was disabled for traditional classic servers. (Before Cataclysm Classic was released)  This was due to the often times severe differences between traditional professions in classic and what's available on retail.  The coding and use of professions in retail was so vastly different that it created a ludicrous amount of bugs.  So that is the only module that was disabled to prevent any possible conflicts with classic servers.

What I will do though is evaluate how it performs in Cataclysm Classic and may possibly enable it from Cataclysm Classic onward.  I can't promise you that I will though, but I will investigate it.  Like I said Retail vs Classic is just crazy in terms of profession changes and coding differences.

**Comment by ThaDanus** [comment]
Clear! Thanks for the superfast explanation!

**Comment by Xruptor** [comment]
No problem.  I do apologize for that but Blizzard did go crazy with profession changes over the years.  Including the coding behind it.  I will look into it though but I believe it's still pretty much the same.
