### ISSUE TITLE
Feature Request: Currency Window - Sort by expansion order, not alphabetical?

### ISSUE THREAD

**Issue by Protuhj** [Xruptor/BagSync#371]
At the very least, put the latest expansion first?

**Comment by Xruptor** [comment]
This has been asked before many times.  Part of the reason it's not been implemented is that Blizzard doesn't really return a sort order for the listed items easily for developers to use.  Also how would I sort a complete list of items if lets say one character has more active currencies then another character.  In that scenario the sort orders would be different then a "master list" per say.  Since BagSync stores ALL currencies from across various characters, it's a bit more difficult to sort them.  Which character would I sort it as as primary and all others as secondary?  It's these complexities that I just made it to be alphabetical.  

I will review the code again for this, but I don't think anything has changed on Blizzards end.  When I call for the Currency list, it doesn't actually return them the way they are displayed on the Currency window.  Still perhaps they have made some changes to it, I can't promise you that it will be implemented, but I can take a look again.

Previous request
https://github.com/Xruptor/BagSync/issues/326#issuecomment-1976861210

**Comment by Protuhj** [comment]
It's all good, if it can't be supported without a huge workaround, then don't worry about it!

**Comment by Xruptor** [comment]
It looks like they are returning it in sort order now.  Perhaps I can work with this and find a solution that works.  I'm testing it to see if it works properly.

**Comment by Xruptor** [comment]
I managed to do a partial implementation of this.  It uses the blizzards expansion level ID to TRY to sort the expansions.  It's not perfect though.  I added an option to turn it off for those that want the old display.
