### ISSUE TITLE
if this suppose to work with  any bag addon

### ISSUE THREAD

**Issue by blecaplol** [Xruptor/BagSync#372]
i think its not working with betterbag. when i hover over the gold its not showing anything

**Comment by Xruptor** [comment]
Gold display in tooltips has never worked for any bag addon with Bagsync. This is because every bag addon handles gold display differently in their code. Especially since each generate their own UI differently. It would be a nightmare to support them all. Ive been asked this many times over the years and its just not feasibly possible. 

Use `/bgs gold` or the Gold option in the minimap button. Otherwise you can setup a keybind for the gold window.
