### ISSUE TITLE
Show currencies across factions

### ISSUE THREAD

**Issue by GreyFoxGer** [Xruptor/BagSync#377]
Can you add an option to show the currencies across horde and alliance together?

**Comment by Xruptor** [comment]
Turning on the option `"Display items for both factions (Alliance/Horde)."` Should do the trick for you.  The currency displayed is tied in with how the tooltip display works.

**Comment by GreyFoxGer** [comment]
It's checked in settings, but not working for me. Only showing for one faction.

**Comment by Xruptor** [comment]
The characters you want to see are probably on a server that isn't connected to the one you are currently on.  Not all servers are connected in WOW.  In general BagSync only shows data from realms that are connected because typically that's the only place you can really trade with characters.  There are some things in WOW that are linked to your Battle.NET account account though.  In which case you have to turn that on.  There is an option to `"Display all Battle.Net account characters. (Not Recommended)"`.  Turn on that option and let me know if that worked for you.

Here is a list of connected realms
https://wowpedia.fandom.com/wiki/Connected_Realms

**Comment by GreyFoxGer** [comment]
It's working, thanks.

**Comment by Xruptor** [comment]
I figured as much.  The characters you want to display are on servers not connected to each other. That's why the BNET option is there, for those that want to see them anyways.
