### ISSUE TITLE
Possibly causing Grid2 raid frames to disappear

### ISSUE THREAD

**Issue by geckzilla** [Xruptor/BagSync#396]
I've been trying to figure out what's causing my raid frames to disappear for weeks now. Hard because I'm usually trying to raid when it happens, but I finally realized I was getting a bug in my Bug Sack that seems like it's coming from BagSync. I'm not going to pretend I have any idea why this is happening. Hopefully it helps, though.

```
2x [ADDON_ACTION_BLOCKED] AddOn 'BagSync' tried to call the protected function 'Grid2LayoutFrame:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPoint'
[string "@Grid2/GridLayout.lua"]:1015: in function `SnapHeaderToPoint'
[string "@Grid2/GridLayout.lua"]:1025: in function <Grid2/GridLayout.lua:1022>
[string "@Grid2/GridLayout.lua"]:1030: in function <Grid2/GridLayout.lua:1029>
[string "@Grid2/GridLayout.lua"]:1036: in function `CheckFrame'
[string "@Grid2/GridLayout.lua"]:1042: in function `SearchSnapToNearestHeader'
[string "@Grid2/GridLayout.lua"]:373: in function `StopMoveFrame'
[string "@Grid2/GridLayout.lua"]:218: in function <Grid2/GridLayout.lua:218>

Locals:
Skipped (In Encounter)
```

**Comment by geckzilla** [comment]
it doesn't make any sense to me so I'm also going to try posting the error to the Grid2 issue tracker...

**Comment by Xruptor** [comment]
This error is not caused by BagSync. However, it's being blamed for another addons bug due to how Blizzards cascading error trapping works. Since BagSync starting with the letter "B" is higher than most other addons alphabetically. If you get it again then let me know, but I suspect it was another addon.  Therefore, since it doesn't know the actual addon that caused the error, it just blames it on the previous one in the memory buffer.  Which can be any addon really that is loaded.  It's not perfect but it tries to pinpoint it the best it can.

This happens a lot and addons usually get blamed incorrectly. This is because it goes down Alphabetically down the Addon list and BagSync is higher up since it starts with a B. In addition Blizzards error trap reporting is not always accurate.

Also I want to point out that there are 3 addons listed in that error. It makes no sense.  BugGrabber, BagSync and Grid.  SetPoint means that a frame window was trying to be moved on the screen.  So something that has to do with moving a frame around.  It's possible it could be BugGrabber but I highly doubt it, more than likely it's Grid.
