### ISSUE TITLE
(minor issue) Count anchor for recipes

### ISSUE THREAD

**Issue by Homaxz** [Xruptor/BagSync#48]
BagSync anchors to the bottom of each tooltip: http://i.imgur.com/Pj4pcQt.jpg
For recipes it looks like this (not at the bottom): http://i.imgur.com/D4UqbF5.jpg

Would be nice to have it at the bottom for recipes, too. For consistency's sake.

Thanks for your great AddOn.

**Comment by Xruptor** [comment]
Sadly, this is a known Blizzard issue.  You see Blizzard treats recipes differently then regular items.  In fact the tooltip is populated three times.  The top portion, center and bottom are dynamically updated.  When grabbing information from the tooltip, there is currently a bug that returns nil with recipes.  This causes a whole heap of issues.  The only way around this that I know of is to add a delay before the details are put into the recipes.  However, this solution would work on ALL tooltips and in order for me to just target Recipes I'd have to check the tooltip strings for something like "Recipe:" in the first line.

It's not impossible just not practical right now because of all the issues and bugs surrounding Recipes.

I want to point out that many addons have this same issue with Recipes, even one as sophisticated as TradeSkillMaster has this issue.  You will notice they too put the information for recipes in the center because of the bugged refresh rate of the recipes tooltip caused by Blizzard bug.  That being said you may find an addon that does solve this issue with the aforementioned delay implementation.  However, I just do not feel comfortable adding such a system right now.

Thanks for pointing out this slight cosmetic bug.  I think it's so minor that it can be gotten used to really.  I wish I had better news for you on this request.

**Comment by Homaxz** [comment]
No worries, as you said I will just get used to it and it's not really worth the hassle as recipes shouldn't be stored anyway. Thanks for the in-depth comment, and your great AddOn!
