### ISSUE TITLE
cross-realm double count guildbank items

### ISSUE THREAD

**Issue by ZappZarap** [Xruptor/BagSync#53]
hi, ok, i try to explain it better here now..

you see on the picture attached, that the guild "Aletheia" is shown tiwce.. ..this is from the original server "Nethersturm" and it also shows the count of "Echteisenerz" ( witch means "True Iron Ore") from the cross-realm "Alexstrasza".. ..that means, it doubles the Summary ("Gesamt" in german)...

again: i have 1950 true iron ore in my guildbank from the guild "Aletheia".. ..i have several chars spread over the two realms nethersturm and alexstrasza.. ..and this happens, if i want so see the summary in the tooltip..

i hope you understand my issue now.. ..sorry, i am not a nativ speaker!

maby the problem is that you can have two guilds named the same on two cross-realms? 

thank you very much.. ..bagsync always was and is my absolut favourit addon managing stuff.

regards, 

zapp

![bagsync screenshot](https://cloud.githubusercontent.com/assets/22418021/18810335/eaf1b380-8293-11e6-8169-1bb100467bfb.png)

**Comment by Xruptor** [comment]
Thanks!  I'll look into it now that you have posted a picture and gave some explanation on the issue.  It may be caused by multiple guilds on the same linked server.  Not entirely sure and will have to look into this myself.  Hmm that or somehow the guild is being picked up twice by the code.  Which is a possibility as well.

Could you do me a favor and attach your BagSync.lua from your SavedVariables?  That way I can look at the values and see what's going on.

You can find it under the following folder on your computer.
World of Warcraft\WTF\<ACCOUNT NAME>\SavedVariables\BagSync.lua

**Comment by ZappZarap** [comment]
no problem.. ..but make sure you delete it afterwards!

hopefully it will help you fix the problem.. ..as you can see the tooltip is rather useless for a quick overview for summary..

thx again


[BagSync.zip](https://github.com/Xruptor/BagSync/files/491426/BagSync.zip)

**Comment by Xruptor** [comment]
Don't worry about the BagSync information.  There is nothing personal in there just the inventory details.  Not like anyone can do anything with that anyways.

Regardless!  I found the issue after looking at your BagSync.lua.

It looks like the guild Aletheia is saved under both Alexstrasza and Nethersturm.  I will admit this is very strange indeed.  I never thought this would ever occur as I figured the guild would be saved on a single realm and not on two realms.  Now all I need to do is find a way for it to save one guild information when it's on two separate servers of which are cross-realm connected.  The data you have in BagSync.lua is like below.

	["Alexstrasza"] = {
		["Phronesis"] = {},
		["Aletheia"] = {},
	},

	["Todeswache"] = {
	},

	["Nethersturm"] = {
		["Bancroft"] = {},
		["Aletheia"] = {},
	}

As you can see Aletheia is under two realms.  I need to compare the data and see if the same items and counts are being reported equally under both.

Thanks for your help.  I'll see if I can find a solution for you soon.

**Comment by ZappZarap** [comment]
sorry i'm not that great programmer but my account was hacked once several years ago..

strange, that this one guild is listed on both realms as a seperate one...

i wonder if only i have this issue??

but for all a big thank you and looking forward to a solution.

regards, 

zapp

**Comment by Xruptor** [comment]
Okay try this version and let me know if it still shows the multiple guilds for you.  It should only be counting the guild once and only display once.

https://github.com/Xruptor/BagSync/archive/v10.5.zip

**Comment by ZappZarap** [comment]
lol.. ..its weird.. ..works now for this one guildbank "Aletheia"... on both realms..

but the items of the guildbank "Phronesis" witch is on Alexstrasza are not shown when i am logged in on Nethersturm.. ..and when i am logged in on Alexstrasza the items of the guildbank "Bancroft" witch is on Nethersturm are not shown... ...crazy somehow :-)

is the problem, that it is all one account? 

but i'm glad it works for the "Main-Guild-Bank" :-)

thank you so far.. ..i imagine its a real puzzle :-)

**Comment by Xruptor** [comment]
I'll look into it.  There is no reason those other guilds would not be showing up.  Yes the issue is that everything is one account.  I didn't anticipate that someone would actually make characters on another server within the same cross-realm group.  Then have those characters all join the same guild.

I just need to find a way around the duplication of guild information.  Since everything is based on the server name.  I'm going to try another way to tackle this problem.

**Comment by Xruptor** [comment]
Okay please try the following changes.
[BagSync-master.zip](https://github.com/Xruptor/BagSync/files/495855/BagSync-master.zip)

I need you to make sure you login to every server you have with at least one character.  Not just the connected ones.

Make sure you have the Battle.Net disabled for the first test.  You should only have the Cross-Realm option enabled.

Please let me know the following:
1) The cross-realm guild should now only display once per character.  Instead of it showing up twice.
2) The other guilds should now properly be showing when you login to other servers. (Remember you won't see all of them because Battle.Net support was disabled).  You will only see the guilds on the cross-realms connected to the current realm you are logged into.

Now enable the Battle.Net option for BagSync.  You should have both the Cross-Realm enabled and the Battle.Net option enabled.

Please let me know the following:
1) The cross-realm guild should only show up once regardless of what server you login.
2) All the other guilds should now properly show up regardless of what server you are on.
3) The tags should be showing up appropriately next to each guild when the Battle.Net option is enabled.

Let me know if this works out for you.  I need to know that you tested it correctly.  It's not recommended to have the Battle.Net option enabled as it will show you everything on every character from every server.  This includes the servers that aren't connected.  That's why sometimes servers show up and others don't.  It depends if you have Cross-Realm enabled AND the Battle.Net option.  Which is why I put (Not recommended) next to the option.  However, people still want to see account information across the board.

Hopefully this change works.  Once again remember you have to login to one character on each server at least once for this to work properly.

**Comment by ZappZarap** [comment]
wow, first of all, thank you very much!

i testet the various steps and it seems to work all as it should so far.. ..amazing!

there is only one minor issue.. ..when bnet otion is enabled (witch i don't need for myselfe because it is not possible to send mats to those not connected realms) the servername will be not displayed in the tooltip for the guild as it does on connected realms.

but now its great for me as i can send all those seldom used things to the xr-guildbank and make room for the main guildbank and still see those items around!

thank you so much!!

another small suggestion.. ..is it possible to shorten the servernames? its a little bit overwhelming in the tooltip..

but thats really not that important..

thank you again :-) good work!

regards

zapp

**Comment by Xruptor** [comment]
The server name isn't supposed to show next to guilds when you are on a cross-realm.  That's because they share the same guild regardless of the realm you are on while you are logged in.  There is no need to put the server name next to it.  The only time you will see the server name for a cross-realm guild is when you aren't logged into a cross-realm server and have the battle.net option enabled.  Even then you will only see it listed once, not twice.

I'm putting two new options in the config panel for BagSync to help with the server names.  I've been meaning to do this anyways as someone asked for this before.  Apparently on Russian and Portuguese servers the names can get very long.

**Comment by Xruptor** [comment]
Can you do me a favor?  Can you post your BagSync.lua file again.  I want to make sure it's working properly.  I need to see the realm-keys to make sure.

**Comment by Xruptor** [comment]
Hey still hoping you can help me out with this.  Been waiting for a reply and your BagSync.lua before I push the new changes live.

**Comment by ZappZarap** [comment]
hi, sorry, i was not at home the last days...

of course i will help you out while i can!

[BagSync.zip](https://github.com/Xruptor/BagSync/files/503547/BagSync.zip)

**Comment by Xruptor** [comment]
Thanks!

**Comment by Xruptor** [comment]
I released version 10.5 on curse and wowinterface.  It has two new options to shorten the server name.  That should help you out.  Thanks again for all your help.
